### ISSUE TITLE
py35 no blake2b

### ISSUE THREAD

**Issue by drandreaskrueger** [polkascan/py-substrate-interface#1]
I very much appreciate your work on this. Great!

Slight issue: [python 3.5](https://github.com/polkascan/py-substrate-interface/blob/master/setup.py#L111) had not [blake2b in hashlib](https://github.com/polkascan/py-substrate-interface/blob/master/substrateinterface/__init__.py#L20). Perhaps you find another way?

Also see [this idea](https://github.com/polkascan/py-scale-codec/issues/4#issuecomment-555935507).

**Comment by drandreaskrueger** [comment]
Just wanted to make sure, and had another look. This is python 3.5.3:

```
import hashlib
for a in sorted(hashlib.algorithms_available):
    print (a)

blake2b512
blake2s256
md4
md5
md5-sha1
ripemd160
sha1
sha224
sha256
sha384
sha512
whirlpool
```

**Comment by emielvanderhoek** [comment]
Correct Python 3.6 and up:
https://zware-cpython.readthedocs.io/en/stable/library/hashlib-blake2.html

**Comment by drandreaskrueger** [comment]
Good that I updated to Debian Buster, now I am a happy py3.7 user.

Better remove these 2 lines then: https://github.com/polkascan/py-substrate-interface/blob/master/setup.py#L110-L111
