### ISSUE TITLE
BTreeSet type Unknown.

### ISSUE THREAD

**Issue by transxask** [polkascan/py-substrate-interface#102]
hello guys!  I created the state storage in my project for example:
`pub ActiveMiners get(fn active_miners): (u32, BTreeSet<T::AccountId>, u32, BTreeSet<T::AccountId>);`.

But when i got this state by `py-substrate-interface` ,  and the err occurred:
`BTreeSet type Unknown`.

How do I parse this type? thanks.

**Comment by arjanz** [comment]
I recently noticed these new type as well, I have already implemented some of them like `HashMap` and `BTreeMap`.  (https://github.com/polkascan/py-scale-codec/commit/842610296766df983fbbefba55fe4b48a524f3dc)

I will update this issue when I added `BTreeSet` as well, have to look into the Substrate repos

**Comment by transxask** [comment]
Thanks very much! Looking forward to add BtreeSet.

**Comment by transxask** [comment]
> I recently noticed these new type as well, I have already implemented some of them like `HashMap` and `BTreeMap`. ([polkascan/py-scale-codec@8426102](https://github.com/polkascan/py-scale-codec/commit/842610296766df983fbbefba55fe4b48a524f3dc))
> 
> I will update this issue when I added `BTreeSet` as well, have to look into the Substrate repos

Thanks very much! Looking forward to add BtreeSet.

**Comment by arjanz** [comment]
Added support in release [0.13.0](https://github.com/polkascan/py-substrate-interface/releases/tag/v0.13.0)

**Comment by transxask** [comment]
> Added support in release [0.13.0](https://github.com/polkascan/py-substrate-interface/releases/tag/v0.13.0)

Thank you!
