### ISSUE TITLE
I can't figure out type_registry_preset and fix scalecodec.exceptions.RemainingScaleBytesNotEmptyException

### ISSUE THREAD

**Issue by facorazza** [polkascan/py-substrate-interface#105]
I couldn't find any channel to get support regarding this package so I'll just open an issue.

I'm using v0.13 of substrate-interface.

When I try to upload a new contract to a node I have running locally, I get the exception `scalecodec.exceptions.RemainingScaleBytesNotEmptyException`. Reading the docs it seems to be a decoding error due to a wrong registry type preset.

I tried both with a canvas node and with a substrate-node extended with the _contracts_ pallet, but I get the same exception with different numbers in `Current offset: 72 / length: 80`.

#84 does not help much. I tried to use different parameters for ss58_format and type_registry_preset, but perhaps I have to supply a custom type_registry_preset.
#85 suggests to upgrade scalecodec but I already have the latest version.
#98 It seems that canvas has some unsupported changes for now, hence the use of the substrate node template.

If I have to supply a custom type_registry_preset where can I find some guidance on how to generate it?

**Comment by arjanz** [comment]
Before I can help you, I need some more context:

* Which node runtime are you using? Is it latest https://github.com/paritytech/canvas-node (and is it runtime 10 as shown in top left of PolkadotJs/app?)
* Which function were you calling with which params when the `RemainingScaleBytesNotEmptyException` was raised? (a code snippet would be helpful) 
* Is it possible to attach the WASM and metadata (or .contract file) so I can try to reproduce the error?

The `RemainingScaleBytesNotEmptyException` is a very generic error message, which occur if somewhere along the process a type is being decoding where the actual data does not match the assumption of the decomposition in the locally stored type registry of the library, so it's difficult to debug with more context.

**Comment by arjanz** [comment]
Recently the contracts-pallet had some type changes btw, which I implemented and could be those are not backwards compatible with e.g. canvas runtime < 10.

**Comment by arjanz** [comment]
I stumbled upon a somewhat unrelated issue with recent automatic encoding `AccountId` types into the SS58 format, which probably was causing the problems. 

I fixed this in https://github.com/polkascan/py-substrate-interface/commit/fc1e6bd28455427d09df60e61657675d0b6157c5 and when I then use `type_registry_preset='canvas'`,  I was able to successfully deploy the flipper contract.

I will make a new release for this soon

**Comment by arjanz** [comment]
https://github.com/polkascan/py-substrate-interface/releases/tag/v0.13.1 is now being pushed to PYPI

**Comment by facorazza** [comment]
Works great! Thank you
Is there something like a discord channel or similar where one could get more of an informal support?

**Comment by arjanz** [comment]
Definitely, we have a tech channel on Element:  https://matrix.to/#/#polkascan:matrix.org?via=matrix.org&via=matrix.parity.io&via=web3.foundation
