### ISSUE TITLE
pip install substrate-interface doesn't work

### ISSUE THREAD

**Issue by VadneyK** [polkascan/py-substrate-interface#107]
running `pip install substrate-interface` doesn't seem to work here.

Config:
MacOS BigSur 11.2.3 M1 chip

![Screen Shot 2021-05-26 at 3 53 10 PM](https://user-images.githubusercontent.com/57117207/119741396-7974a400-be3a-11eb-86c4-77ea5b423346.png)

Error Message:::

(env) kentarovadney@Kentaros-MacBook-Air substrate-faucet % pip install -r requirements.txt 
Requirement already satisfied: discord in ./env/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.0.1)
Collecting substrate-interface
  Using cached substrate_interface-0.13.4-py3-none-any.whl (171 kB)
Requirement already satisfied: discord.py>=1.0.1 in ./env/lib/python3.9/site-packages (from discord->-r requirements.txt (line 1)) (1.7.2)
Requirement already satisfied: aiohttp<3.8.0,>=3.6.0 in ./env/lib/python3.9/site-packages (from discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (3.7.4.post0)
Requirement already satisfied: yarl<2.0,>=1.0 in ./env/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: multidict<7.0,>=4.5 in ./env/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (5.1.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./env/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in ./env/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (3.10.0.0)
Requirement already satisfied: attrs>=17.3.0 in ./env/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (21.2.0)
Requirement already satisfied: chardet<5.0,>=2.0 in ./env/lib/python3.9/site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna>=2.0 in ./env/lib/python3.9/site-packages (from yarl<2.0,>=1.0->aiohttp<3.8.0,>=3.6.0->discord.py>=1.0.1->discord->-r requirements.txt (line 1)) (2.8)
Collecting py-sr25519-bindings~=0.1.2
  Using cached py_sr25519_bindings-0.1.2.tar.gz (12 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting requests~=2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting base58~=2.0.1
  Using cached base58-2.0.1-py3-none-any.whl (4.3 kB)
Collecting scalecodec~=0.11.6
  Using cached scalecodec-0.11.6-py3-none-any.whl (61 kB)
Collecting py-ed25519-bindings~=0.1.2
  Using cached py_ed25519_bindings-0.1.2.tar.gz (9.0 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting certifi>=2020.11.8
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting websocket-client~=0.58.0
  Using cached websocket_client-0.58.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: xxhash>=1.3.0 in ./env/lib/python3.9/site-packages (from substrate-interface->-r requirements.txt (line 2)) (1.3.0)
Collecting py-bip39-bindings~=0.1.6
  Using cached py_bip39_bindings-0.1.6.tar.gz (7.8 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./env/lib/python3.9/site-packages (from requests~=2.25.1->substrate-interface->-r requirements.txt (line 2)) (1.25.3)
Requirement already satisfied: more-itertools in ./env/lib/python3.9/site-packages (from scalecodec~=0.11.6->substrate-interface->-r requirements.txt (line 2)) (8.8.0)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: py-bip39-bindings, py-ed25519-bindings, py-sr25519-bindings
  Building wheel for py-bip39-bindings (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9 /Users/kentarovadney/Desktop/code/substrate-faucet/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/tmpxfmgj72p
       cwd: /private/var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/pip-install-e52lggfn/py-bip39-bindings_523e06b19039458aa80c18bd64e5ba30
  Complete output (69 lines):
  Running `maturin pep517 build-wheel -i /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9`
     Compiling proc-macro2 v1.0.27
     Compiling unicode-xid v0.2.2
     Compiling syn v1.0.72
     Compiling libc v0.2.95
     Compiling autocfg v0.1.7
     Compiling rand_core v0.4.2
     Compiling typenum v1.13.0
     Compiling autocfg v1.0.1
     Compiling semver-parser v0.7.0
     Compiling serde_derive v1.0.126
     Compiling maybe-uninit v2.0.0
     Compiling proc-macro-hack v0.5.19
     Compiling serde v1.0.126
     Compiling ryu v1.0.5
     Compiling byteorder v1.4.3
     Compiling cc v1.0.68
     Compiling scopeguard v0.3.3
     Compiling serde_json v1.0.64
     Compiling byte-tools v0.3.1
     Compiling itoa v0.4.7
     Compiling gimli v0.24.0
     Compiling regex-syntax v0.6.25
     Compiling failure_derive v0.1.8
     Compiling subtle v1.0.0
     Compiling adler v1.0.2
     Compiling inventory v0.1.10
     Compiling cfg-if v1.0.0
     Compiling scopeguard v1.1.0
     Compiling object v0.24.0
     Compiling version_check v0.9.3
     Compiling smallvec v1.6.1
     Compiling unindent v0.1.7
     Compiling cfg-if v0.1.10
     Compiling rustc-demangle v0.1.19
     Compiling opaque-debug v0.2.3
     Compiling fake-simd v0.1.2
     Compiling rand_core v0.3.1
     Compiling semver v0.9.0
     Compiling rand_chacha v0.1.1
     Compiling rand_pcg v0.1.2
     Compiling rand v0.6.5
     Compiling miniz_oxide v0.4.4
     Compiling num-traits v0.2.14
     Compiling lock_api v0.1.5
     Compiling hashbrown v0.1.8
     Compiling block-padding v0.1.5
     Compiling lock_api v0.3.4
  error: could not compile `lock_api`
  
  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib -- -C link-arg=-undefined -C link-arg=dynamic_lookup -C link-args=-Wl,-install_name,@rpath/bip39.cpython-39-darwin.so`
  🔗 Found pyo3 bindings
  🐍 Found CPython 3.9 at /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9
  error[E0554]: `#![feature]` may not be used on the stable release channel
    --> /Users/kentarovadney/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/lib.rs:91:34
     |
  91 | #![cfg_attr(feature = "nightly", feature(const_fn))]
     |                                  ^^^^^^^^^^^^^^^^^
  
  
  error: aborting due to previous error
  
  
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for py-bip39-bindings
  Building wheel for py-ed25519-bindings (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9 /Users/kentarovadney/Desktop/code/substrate-faucet/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/tmpnvr1ji_x
       cwd: /private/var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/pip-install-e52lggfn/py-ed25519-bindings_a5e2836a3d3c4ed3b15f961c200a55f2
  Complete output (51 lines):
  Running `maturin pep517 build-wheel -i /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9`
     Compiling proc-macro2 v1.0.27
     Compiling unicode-xid v0.2.2
     Compiling syn v1.0.72
     Compiling libc v0.2.95
     Compiling version_check v0.9.3
     Compiling serde v1.0.126
     Compiling rand_core v0.4.2
     Compiling autocfg v0.1.7
     Compiling serde_derive v1.0.126
     Compiling typenum v1.13.0
     Compiling proc-macro-hack v0.5.19
     Compiling getrandom v0.1.16
     Compiling cfg-if v1.0.0
     Compiling ryu v1.0.5
     Compiling serde_json v1.0.64
     Compiling itoa v0.4.7
     Compiling regex-syntax v0.6.25
     Compiling autocfg v1.0.1
     Compiling ppv-lite86 v0.2.10
     Compiling unindent v0.1.7
     Compiling cfg-if v0.1.10
     Compiling scopeguard v1.1.0
     Compiling inventory v0.1.10
     Compiling smallvec v1.6.1
     Compiling signature v1.3.0
     Compiling opaque-debug v0.3.0
     Compiling subtle v2.4.0
     Compiling byteorder v1.4.3
     Compiling rand_core v0.3.1
  error: could not compile `subtle`
  
  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib -- -C link-arg=-undefined -C link-arg=dynamic_lookup -C link-args=-Wl,-install_name,@rpath/ed25519.cpython-39-darwin.so`
  🔗 Found pyo3 bindings
  🐍 Found CPython 3.9 at /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9
  error[E0554]: `#![feature]` may not be used on the stable release channel
    --> /Users/kentarovadney/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-2.4.0/src/lib.rs:12:34
     |
  12 | #![cfg_attr(feature = "nightly", feature(external_doc))]
     |                                  ^^^^^^^^^^^^^^^^^^^^^
  
  
  error: aborting due to previous error
  
  
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for py-ed25519-bindings
  Building wheel for py-sr25519-bindings (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9 /Users/kentarovadney/Desktop/code/substrate-faucet/env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/tmpzn_z8c25
       cwd: /private/var/folders/r_/74rntmcx51zgp8k_z7xncyq00000gn/T/pip-install-e52lggfn/py-sr25519-bindings_2e2176d3d3a2457dba4d03b65e0d31be
  Complete output (54 lines):
  Running `maturin pep517 build-wheel -i /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9`
     Compiling proc-macro2 v1.0.27
     Compiling unicode-xid v0.2.2
     Compiling syn v1.0.72
     Compiling libc v0.2.95
     Compiling getrandom v0.1.16
     Compiling typenum v1.13.0
     Compiling proc-macro-hack v0.5.19
     Compiling serde_derive v1.0.126
     Compiling cfg-if v1.0.0
     Compiling serde v1.0.126
     Compiling ryu v1.0.5
     Compiling byteorder v1.4.3
     Compiling serde_json v1.0.64
     Compiling autocfg v1.0.1
     Compiling itoa v0.4.7
     Compiling byte-tools v0.3.1
     Compiling regex-syntax v0.6.25
     Compiling inventory v0.1.10
     Compiling unindent v0.1.7
     Compiling ppv-lite86 v0.2.10
     Compiling version_check v0.9.3
     Compiling scopeguard v1.1.0
     Compiling cfg-if v0.1.10
     Compiling smallvec v1.6.1
     Compiling keccak v0.1.0
     Compiling fake-simd v0.1.2
     Compiling opaque-debug v0.2.3
     Compiling subtle v2.4.0
     Compiling arrayref v0.3.6
     Compiling arrayvec v0.5.2
     Compiling block-padding v0.1.5
     Compiling lock_api v0.3.4
  error: could not compile `lock_api`
  
  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib -- -C link-arg=-undefined -C link-arg=dynamic_lookup -C link-args=-Wl,-install_name,@rpath/sr25519.cpython-39-darwin.so`
  🔗 Found pyo3 bindings
  🐍 Found CPython 3.9 at /Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9
  error[E0554]: `#![feature]` may not be used on the stable release channel
    --> /Users/kentarovadney/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/lib.rs:91:34
     |
  91 | #![cfg_attr(feature = "nightly", feature(const_fn))]
     |                                  ^^^^^^^^^^^^^^^^^
  
  
  error: aborting due to previous error
  
  
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for py-sr25519-bindings
Failed to build py-bip39-bindings py-ed25519-bindings py-sr25519-bindings
ERROR: Could not build wheels for py-bip39-bindings, py-ed25519-bindings, py-sr25519-bindings which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the '/Users/kentarovadney/Desktop/code/substrate-faucet/env/bin/python3.9 -m pip install --upgrade pip' command.

**Comment by arjanz** [comment]
I think it is the new M1 chip that cannot use the pre-compiled binaries of the required RUST-bindings for Mac (e.g. `py_bip39_bindings-0.1.6-cp39-cp39-macosx_10_7_x86_64.whl` in https://pypi.org/project/py-bip39-bindings/#files).

Then it tries to compile from source, but probably you don't have a RUST development env on your machine. I will try to find a runner with the M1 chip and add the pre-compiled binaries to PYPI. 

In the meantime you could go through the steps described in https://substrate.dev/docs/en/knowledgebase/getting-started/ to be able to install the RUST bindings from source

**Comment by arjanz** [comment]
Ok I compile and uploaded the binaries for `py-bip39-bindings`, `py-sr25519-bindings` and `py-ed25519-bindings`, so the good news is those packages can be used in an MacOS M1 arm setup. 

The bad news is that when I tried to install `substrate-interface` on M1 I stumbled upon the same issue for package `xxhash`. So the same steps applies for that package, this is out of our control but I can post an issue in their [repos](https://github.com/ifduyue/python-xxhash) to assist with this

**Comment by VadneyK** [comment]
I saw you made this issue request: https://github.com/ifduyue/python-xxhash/issues/46

thanks! hope this gets resolved soon!

**Comment by PaTara43** [comment]
> Ok I successfully compiled and uploaded the binaries for `py-bip39-bindings`, `py-sr25519-bindings` and `py-ed25519-bindings`, so the good news is those packages can be used in an MacOS M1 arm setup.
> 
> The bad news is that when I tried to install `substrate-interface` on M1 I stumbled upon the same issue for package `xxhash`. So the same steps applies for that package, this is out of our control but I can post an issue in their [repos](https://github.com/ifduyue/python-xxhash) to assist with this

Hello, is it possible to do the same for ARM for RPI with raspbian/ubuntu server?
Otherwise it take a lot of time to compile

**Comment by arjanz** [comment]
Install on raspbian/ubuntu now successfully uses pre-compiled wheels for all dependencies.
