### ISSUE TITLE
Extrinsic destination for some transfers is encoded as "0x[ss58_encoding]"

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-substrate-interface#108]
After upgrading to v0.13.4 from v0.12.1, it seems that addresses in the extrinsics retrieved through `get_block()` call are pre-encoded to ss58. 
However, some of them (so far seen only those appearing in params -> dest) are prefixed with "0x". 
For instance '0x1nSRbbdKMefbPiU4AvHLwxrUSLp7p95gMuvc5zj8wjecjBh'.
Is there any reason for this? It looks like a bug - trying to match this to a transfer event fails, because in the event it appears without the prefix.

**Comment by arjanz** [comment]
Can you provide an example block_hash (if it's one of the public networks) so I can reproduce this? The transfers I checked seems ok..

**Comment by arjanz** [comment]
Ok reproduced, when I encode and then decode an extrinsic I get the same issue

**Comment by arjanz** [comment]
Released in https://github.com/polkascan/py-substrate-interface/releases/tag/v0.13.5
