### ISSUE TITLE
Could not decode `MultiAddress`, variant doesn\\\'t exist

### ISSUE THREAD

**Issue by rupansh** [polkascan/py-substrate-interface#110]
Code:
```
        call = substrate.compose_call(
            call_module='Balances',
            call_function='transfer',
            call_params={
                'dest': '5E9oDs9PjpsBbxXxRE9uMaZZhnBAV38n2ouLB28oecBDdeQo',
                'value': 10**16
            }
        )
        ext = substrate.create_signed_extrinsic(call, polka.sender)
        substrate.submit_extrinsic(ext, wait_for_inclusion=True)
```

Error:
```
    raise SubstrateRequestException(message['error'])
substrateinterface.exceptions.SubstrateRequestException: {'code': 1002, 'message': 'Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: Could not decode `MultiAddress`, variant doesn\\\'t exist")', 'data': 'RuntimeApi("Execution failed: ApiError(\\"Could not convert parameter `tx` between node and runtime: Could not decode `MultiAddress`, variant doesn\\\\\\\'t exist\\")")'}
```

**Comment by arjanz** [comment]
* Which network and runtime_id is the node you are connecting with?
* Which `type_registry_preset` are you using in the constructor?

**Comment by rupansh** [comment]
>     * Which network and runtime_id is the node you are connecting with?
> 
>     * Which `type_registry_preset` are you using in the constructor?
> 
>     * Is the package `scalecodec` up to date?

1.local substrate node
2. `substrate-node-template`
3. I did not explicitly install this but `0.11.9`

**Comment by arjanz** [comment]
Ok.. I think the `substrate-node-template` type registry preset is out-of-date, I will have a look at this and release an update (probably tomorrow with other updates).

Could be they updated to latest Substrate version, what you could try in the meantime is set `type_registry_preset=default` and see if that works, or cross-check the runtime_id visible in PolkadotJS-apps and see what is the latest version in https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/substrate-node-template.json (should use `MultiAddress`)

**Comment by rupansh** [comment]
> Ok.. I think the `substrate-node-template` type registry preset is out-of-date, I will have a look at this and release an update (probably tomorrow with other updates).
> 
> Could be they updated to latest Substrate version, what you could try in the meantime is set `type_registry_preset=default` and see if that works, or cross-check the runtime_id visible in PolkadotJS-apps and see what is the latest version in https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/substrate-node-template.json (should use `MultiAddress`)

setting type_registry_preset='default' is working for now.
Thanks for the quick help!

**Comment by arjanz** [comment]
I compiled latest node-template from https://github.com/substrate-developer-hub/substrate-node-template/ and tried a balance transfer with `type_registry_preset=substrate-node-template` and it seems to work though..

I'm seeing runtime 100 in Polkadot-JS apps:
<img width="171" alt="Screenshot 2021-06-07 at 10 41 42" src="https://user-images.githubusercontent.com/5286904/120986785-3d680a00-c77d-11eb-8ab9-161a2385e593.png">

Which runtime ID are you running?

**Comment by rupansh** [comment]
> I compiled latest node-template from https://github.com/substrate-developer-hub/substrate-node-template/ and tried a balance transfer with `type_registry_preset=substrate-node-template` and it seems to work though..
> 
> I'm seeing runtime 100 in Polkadot-JS apps:
> <img alt="Screenshot 2021-06-07 at 10 41 42" width="171" src="https://user-images.githubusercontent.com/5286904/120986785-3d680a00-c77d-11eb-8ab9-161a2385e593.png">
> 
> Which runtime ID are you running?

It seems that i was on `node-frontier-template` instead of `substrate-node-template`!
