### ISSUE TITLE
Allow to define custom ss58 format for decode/encode

### ISSUE THREAD

**Issue by vikiival** [polkascan/py-substrate-interface#111]
**How it works**
Currently, decode and encode [functions](https://polkascan.github.io/py-substrate-interface/#substrateinterface.SubstrateInterface.ss58_decode) takes only one argument which is address

**What would be nice**

I would like to have another optional argument which is `ss58_format`

**Why**

Even though I am connected to the Kusama I would like to know the decoded/encoded address in other formats (eg `42`)

**Comment by arjanz** [comment]
Actually these functions are just a thin convenience layer for `substrateinterface.utils.ss58_encode` and `substrateinterface.utils.ss58_encode`, so you can just import them if you require another SS58 format..

**Comment by arjanz** [comment]
See https://polkascan.github.io/py-substrate-interface/utils/ss58.html for more information
