### ISSUE TITLE
NotImplementedError: Decoder class for "xxxxxxxxxxxxxxx" not found

### ISSUE THREAD

**Issue by 99Kies** [polkascan/py-substrate-interface#113]
my pallet func
![image](https://user-images.githubusercontent.com/45918704/121776512-dc4a9700-cbbf-11eb-97e4-d9c734a69ddf.png)

python func
![image](https://user-images.githubusercontent.com/45918704/121776618-727ebd00-cbc0-11eb-88a9-36750c9e1675.png)

**Comment by arjanz** [comment]
When you see these kind of exceptions, it means the library doesn't know how to decode these types defined in your runtime. 

You need to create a dict with the format described in https://github.com/polkascan/py-substrate-interface#substrate-node-template and search the type(s) mentioned and enter the decomposition. 

You can find an exhaustive list of types known to `py-substrate-interface` here:  https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/default.json So basically you need to add the types like `<T as frame_system::Config>::BlockNumber` which probably is just is a `BlockNumber`

**Comment by 99Kies** [comment]
> When you see these kind of exceptions, it means the library doesn't know how to decode these types defined in your runtime.
> 
> You need to create a dict with the format described in https://github.com/polkascan/py-substrate-interface#substrate-node-template and search the type(s) mentioned and enter the decomposition.
> 
> You can find an exhaustive list of types known to `py-substrate-interface` here: https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/default.json So basically you need to add the types like `<T as frame_system::Config>::BlockNumber` which probably is just is a `BlockNumber`

So how do I add my type here? By the way, is there any automatic generating tool? This sounds to me like an **ABI** file in Solidity

**Comment by 99Kies** [comment]
add 
```
    "<T as frame_system::Config>::BlockNumber": "u64",
```
thanks.

**Comment by arjanz** [comment]
> So how do I add my type here?

As I mentioned above, this is described here: https://github.com/polkascan/py-substrate-interface#substrate-node-template

> By the way, is there any automatic generating tool? This sounds to me like an **ABI** file in Solidity

Unfortunately until now there is no automatic introspection of the runtime, so you will have to administer this yourself. However there is a project active to facilitate this in the near future: https://github.com/paritytech/scale-info

Good luck!

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/121927480-ac42f580-cd71-11eb-880f-5fffe7a12a01.png)

How can I use `substrate.query(xxxx)` to implement a query with no parameters.
![image](https://user-images.githubusercontent.com/45918704/121927659-e4e2cf00-cd71-11eb-8a8a-7b2cc56231f3.png)

**Comment by 99Kies** [comment]
> > So how do I add my type here?
> 
> As I mentioned above, this is described here: https://github.com/polkascan/py-substrate-interface#substrate-node-template
> 
> > By the way, is there any automatic generating tool? This sounds to me like an **ABI** file in Solidity
> 
> Unfortunately until now there is no automatic introspection of the runtime, so you will have to administer this yourself. However there is a project active to facilitate this in the near future: https://github.com/paritytech/scale-info
> 
> Good luck!

This is a really great project!

**Comment by arjanz** [comment]
> ![image](https://user-images.githubusercontent.com/45918704/121927480-ac42f580-cd71-11eb-880f-5fffe7a12a01.png)
> 
> How can I use `substrate.query(xxxx)` to implement a query with no parameters.
> ![image](https://user-images.githubusercontent.com/45918704/121927659-e4e2cf00-cd71-11eb-8a8a-7b2cc56231f3.png)

You are probably looking for https://github.com/polkascan/py-substrate-interface#query-a-mapped-storage-function

**Comment by 99Kies** [comment]
yes, thanks!!! @arjanz
