### ISSUE TITLE
I can't get the value of the other parameter.

### ISSUE THREAD

**Issue by 99Kies** [polkascan/py-substrate-interface#114]
![image](https://user-images.githubusercontent.com/45918704/121978271-7118e480-cdba-11eb-90da-15ea8ba78dbb.png)

I can't get the value of the other parameter. Here the BlockNumber is displayed on `polkdot.js` but it only gets the value of None when using `Query-Map`
![image](https://user-images.githubusercontent.com/45918704/121978214-4b8bdb00-cdba-11eb-90c5-0b92c9a07ce4.png)

**Comment by arjanz** [comment]
Then probably a decoding error occurred when decoding `BlockNumber`. You can verify this by providing `ignore_decoding_errors=False` in the `query_map` function and step through the decoding . 

Perhaps the `BlockNumber` you mentioned is not correct in your case? Have you tried `u32`, `u64`, `Compact<u32>`?

**Comment by 99Kies** [comment]
thanks, need choice `u32`
