### ISSUE TITLE
Proof of Existence

### ISSUE THREAD

**Issue by cyrilnavessamuel** [polkascan/py-substrate-interface#115]
Hello, 
I am not sure If this is an issue but feel free to close this if not appropriate.

I am facing an issue when trying Proof of Existence example in substrate:

I try to call as:

from substrateinterface import SubstrateInterface, Keypair

substrate = SubstrateInterface(url="http://127.0.0.1:9933")

keypair = Keypair.create_from_mnemonic('episode together nose spoon dose oil faculty zoo ankle evoke admit walnut')

call = substrate.compose_call(
    call_module='templateModule',
    call_function='createClaim',
    call_params={
        'proof': '5E9oDs9PjpsBbxXxRE9uMaZZhnBAV38n2ouLB28oecBDdeQo',

    }
)

extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)

try:
    receipt = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)
    print("Extrinsic '{}' sent and included in block '{}'".format(receipt.extrinsic_hash, receipt.block_hash))

except SubstrateRequestException as e:
    print("Failed to send: {}".format(e))
_______________________________________________

I am getting an error as: raise MetadataCallFunctionNotFound(
scalecodec.exceptions.MetadataCallFunctionNotFound: Call function 'templateModule.createClaim' not found in metadata

Could you please let me know what am I doing wrong?

Also can you please let me know the channel where I can ask my queries?

Thanks in advance,
Cyril

**Comment by arjanz** [comment]
There is either a typo in the pallet name, or the call function name.. 

You can get a complete list of available call functions with: `substrate.get_metadata_call_functions()`

From my experience is the casing is maybe incorrect, maybe its `create_claim`?

**Comment by arjanz** [comment]
And don't forget to provide supply the correct type_registry_preset in the constructor (I assume node-template), and replace the http with the websocket endpoint to enable the possibility of subscriptions:

```python
substrate = SubstrateInterface(url="ws://127.0.0.1:9944", type_registry_preset='substrate-node-template')
```

**Comment by arjanz** [comment]
For more info check: https://github.com/polkascan/py-substrate-interface#substrate-node-template

**Comment by cyrilnavessamuel** [comment]
Thanks arjanz, It solved my problem!

Just a question when I create a new keypair from a random mnemonic , can I just use to send a transaction create_claim or should I deposit some tokens in my account. Because I get an error: Failed to send: {'code': 1010, 'message': 'Invalid Transaction', 'data': 'Inability to pay some fees (e.g. account balance too low)'} .Just to explain the context I use the proof of existence example

**Comment by arjanz** [comment]
Yes the created account should have a balance in order to pay the transactions fees

**Comment by sennhvi** [comment]
> 

TemplateModule .create_claim
