### ISSUE TITLE
Type generation from MetadataV14

### ISSUE THREAD

**Issue by arjanz** [polkascan/py-substrate-interface#117]
paritytech/substrate#8615

https://github.com/polkadot-js/api/issues/3687

**Comment by PierreBesson** [comment]
FYI, V14 metadata support is now required to connect to Rococo since its recent relaunch.

**Comment by arjanz** [comment]
Merged PR and released in https://github.com/polkascan/py-substrate-interface/releases/tag/v1.0.0
