### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by 99Kies** [polkascan/py-substrate-interface#121]
![image](https://user-images.githubusercontent.com/45918704/124217267-a3507300-db2a-11eb-8e59-25a587970792.png)

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/124217471-fc200b80-db2a-11eb-8bb1-fabca1d7e0e4.png)

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/124218052-08f12f00-db2c-11eb-8321-a617e27c0011.png)
![image](https://user-images.githubusercontent.com/45918704/124218091-1dcdc280-db2c-11eb-9826-a6c6cca0c8a7.png)
and, I can't get all the values through this tool.

**Comment by 99Kies** [comment]
How to solve this problem correctly.
![image](https://user-images.githubusercontent.com/45918704/124219326-b9f8c900-db2e-11eb-8b1d-3179f61fcc5b.png)

**Comment by 99Kies** [comment]
I solved this.

**Comment by ToufeeqP** [comment]
@99Kies I am getting the same error, May I know how did you solved this?

**Comment by 99Kies** [comment]
> @99Kies I am getting the same error, May I know how did you solved this?

You need to add the data type you set in default.json.
https://github.com/polkascan/py-substrate-interface/issues/121#issuecomment-872690411

**Comment by 99Kies** [comment]
> @99Kies I am getting the same error, May I know how did you solved this?

You need to be aware that when calling this method it is best to distinguish between a Value and a Map.
