### ISSUE TITLE
ValueError(f'Unsupported type registry preset "{name}"')

### ISSUE THREAD

**Issue by lana-shanghai** [polkascan/py-substrate-interface#122]
Hey Arjan, I have been struggling with passing my custom types file to the interface class. Do you know how I could pass the file or dictionary properly to the interface? :)

Here is where I define the types dictionary and the Substrate interface class: 

`custom_type_registry = {
    "types": {
        "Address": "MultiAddress",
        "LookupSource": "MultiAddress",
        "Bid": {
        "uuid": "u32",
        "market_uuid": "Option<Vec<u8>>",
        "asset_uuid": "Option<Vec<u8>>",
        "max_energy": "u32",
        "time_slot": "Vec<u8>"
        },
        "Offer": {
        "uuid": "u32",
        "market_uuid": "Option<Vec<u8>>",
        "asset_uuid": "Option<Vec<u8>>",
        "energy_type": "Vec<u8>",
        "max_energy": "u32",
        "time_slot": "Vec<u8>"
        },
        "Match": {
        "ids": "u32",
        "price": "u32",
        "energy": "u32"
        }
    }
}

class BlockChainInterface:

    def __init__(self):
        self.substrate = SubstrateInterface(
            url=DEFAULT_SUBSTRATE_URL,
            address_type=TEMPLATE_NODE_ADDRESS_TYPE,
            type_registry=custom_type_registry,
            use_remote_preset=False
        )`

Here is the traceback:

`
Traceback (most recent call last):
  File "/Users/admin/Envs/d3a/bin/d3a", line 33, in <module>
    sys.exit(load_entry_point('d3a', 'console_scripts', 'd3a')())
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/github/d3a/src/d3a/d3a_core/cli.py", line 151, in run
    run_simulation(setup_module_name, simulation_config, None, None, None,
  File "/Users/admin/github/d3a/src/d3a/d3a_core/simulation.py", line 592, in run_simulation
    simulation = Simulation(
  File "/Users/admin/github/d3a/src/d3a/d3a_core/simulation.py", line 120, in __init__
    self._init(**self.initial_params, redis_job_id=redis_job_id)
  File "/Users/admin/github/d3a/src/d3a/d3a_core/simulation.py", line 185, in _init
    self.bc = BlockChainInterface()
  File "/Users/admin/github/d3a/src/d3a/blockchain/__init__.py", line 64, in __init__
    self.substrate = SubstrateInterface(
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/substrateinterface/base.py", line 450, in __init__
    self.reload_type_registry(use_remote_preset=use_remote_preset)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/substrateinterface/base.py", line 2496, in reload_type_registry
    type_registry_preset_dict = load_type_registry_preset(self.chain.lower())
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/scalecodec/type_registry/__init__.py", line 43, in load_type_registry_preset
    raise ValueError(f'Unsupported type registry preset "{name}"')
ValueError: Unsupported type registry preset "local testnet"
`

**Comment by arjanz** [comment]
Is your node a fork from https://github.com/substrate-developer-hub/substrate-node-template or https://github.com/paritytech/substrate? Then the `type_registry_preset` should be set to resp. `substrate-node-template` or `development`. 

Because when you leave out the `type_registry_preset` it tries to 'autodiscover' by it's chain name, which will work for e.g. kusama and polkadot, but not for unknown chains. 

Also `address_type` has been deprecated in favor of `ss58_format`. `type_registry` should indeed be a dict and I saw `custom_type_registry` is already in the good format.

So you can try:

```python
self.substrate = SubstrateInterface(
    url=DEFAULT_SUBSTRATE_URL,
    ss58_format=TEMPLATE_NODE_ADDRESS_TYPE, # defaults to 42 if omitted
    type_registry_preset='substrate-node-template', # or 'development' depending on base
    type_registry=custom_type_registry
)

```

I can imagine it can be a bit confusing to find to right combination of parameters, perhaps I should make a few class methods like I did with `Keypair` to make it simpler to initialize.

**Comment by arjanz** [comment]
I did notice the structs in `custom_type_registry` are in the format for PolkadotJS, but to use with `SubstrateInterface` you need to reformat the dict a bit, you can check out https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/type_registry/polkadot.json#L10 for examples of the correct format of structs and enums

**Comment by lana-shanghai** [comment]
@arjanz the template I'm using is this one: https://github.com/substrate-developer-hub/substrate-parachain-template
Which preset do I use here then? :) development?

**Comment by arjanz** [comment]
@lana-shanghai good question, I haven't checked out that template yet :) I read over there substrate-parachain-template is a fork of substrate-node-template, so I guess that's your best bet. 

Let me know if you have any decoding problems, then I will make a preset for this template as well

**Comment by lana-shanghai** [comment]
Ok, will try it out and let you know! Thanks :)

**Comment by lana-shanghai** [comment]
Hey Arjan! I am sadly bumping into decoding errors as the dictionary is wrong, but I tried to make it as close to what you sent me above. This line https://github.com/polkascan/py-scale-codec/blob/9c14f5837513d5ce0052db5efaad3b9d8b48079c/scalecodec/base.py#L167 tries to access the `type` key but that key is inside another dictionary with `types` key. Some help with this template would be very appreciated :) 

```
custom_type_registry = {
    "runtime_id": 2000,
    "types":{
        "Address": "MultiAddress",
        "LookupSource": "MultiAddress",
        "Keys": {
            "type": "struct",
            "type_mapping": [
                ["grandpa", "AccountId"],
                ["babe", "AccountId"],
                ["im_online", "AccountId"],
                ["authority_discovery", "AccountId"],
                ["parachains", "AccountId"]
            ]
        },
        "Bid": {
        "uuid": "u32",
        "market_uuid": "Option<Vec<u8>>",
        "asset_uuid": "Option<Vec<u8>>",
        "max_energy": "u32",
        "time_slot": "Vec<u8>"
        },
        "Offer": {
        "uuid": "u32",
        "market_uuid": "Option<Vec<u8>>",
        "asset_uuid": "Option<Vec<u8>>",
        "energy_type": "Vec<u8>",
        "max_energy": "u32",
        "time_slot": "Vec<u8>"
        },
        "Match": {
        "ids": "u32",
        "price": "u32",
        "energy": "u32"
    }
  }
}
```

```
Traceback (most recent call last):
  File "/Users/admin/Envs/d3a/bin/d3a", line 33, in <module>
    sys.exit(load_entry_point('d3a', 'console_scripts', 'd3a')())
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/admin/github/d3a/src/d3a/d3a_core/cli.py", line 151, in run
    run_simulation(setup_module_name, simulation_config, None, None, None,
  File "/Users/admin/github/d3a/src/d3a/d3a_core/simulation.py", line 592, in run_simulation
    simulation = Simulation(
  File "/Users/admin/github/d3a/src/d3a/d3a_core/simulation.py", line 120, in __init__
    self._init(**self.initial_params, redis_job_id=redis_job_id)
  File "/Users/admin/github/d3a/src/d3a/d3a_core/simulation.py", line 185, in _init
    self.bc = BlockChainInterface()
  File "/Users/admin/github/d3a/src/d3a/blockchain/__init__.py", line 75, in __init__
    self.substrate = SubstrateInterface(
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/substrateinterface/base.py", line 450, in __init__
    self.reload_type_registry(use_remote_preset=use_remote_preset)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/substrateinterface/base.py", line 2515, in reload_type_registry
    self.runtime_config.update_type_registry(self.type_registry)
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/scalecodec/base.py", line 222, in update_type_registry
    self.update_type_registry_types(type_registry.get('types'))
  File "/Users/admin/Envs/d3a/lib/python3.8/site-packages/scalecodec/base.py", line 167, in update_type_registry_types
    if decoder_class_data['type'] == 'struct':
KeyError: 'type'
```

**Comment by arjanz** [comment]
The struct format of `Bid`, `Offer` and `Match` is incorrect, it should be formatted like `Keys`

**Comment by lana-shanghai** [comment]
Ahaa, let me fix that up. And the `KeyError: 'type'` stems from that?

**Comment by arjanz** [comment]
Exactly, that is missing now :)

**Comment by lana-shanghai** [comment]
This worked! Thanks for the help! 😄

```
custom_type_registry = {
    "runtime_id": 2000,
    "types": {
        "Address": "MultiAddress",
        "LookupSource": "MultiAddress",
        "Keys": {
            "type": "struct",
            "type_mapping": [
                ["grandpa", "AccountId"],
                ["babe", "AccountId"],
                ["im_online", "AccountId"],
                ["authority_discovery", "AccountId"],
                ["parachains", "AccountId"],
                ["Bid",
                    [
                        ["uuid", "u32"],
                        ["max_energy", "u32"],
                        ["market_uuid", "Option<Vec<u8>>"],
                        ["asset_uuid", "Option<Vec<u8>>"],
                        ["time_slot", "Vec<u8>"]
                    ]
                ],
                ["Offer",
                    [
                        ["uuid", "u32"],
                        ["max_energy", "u32"],
                        ["market_uuid", "Option<Vec<u8>>"],
                        ["asset_uuid", "Option<Vec<u8>>"],
                        ["energy_type", "Vec<u8>"],
                        ["time_slot", "Vec<u8>"]
                    ]
                ],
                ["Match",
                    [
                        ["ids", "u32"],
                        ["price", "u32"],
                        ["energy", "u32"]
                    ]
                ]

            ]
        }
    }
}
```

**Comment by arjanz** [comment]
I'm afraid `Bid`, `Offer` and `Match` are still incorrect, they are now part of the `Keys` struct.

It should be something like:

```
custom_type_registry = {
    "runtime_id": 2000,
    "types": {
        "Address": "MultiAddress",
        "LookupSource": "MultiAddress",
        "Keys": {
            "type": "struct",
            "type_mapping": [
                ["grandpa", "AccountId"],
                ["babe", "AccountId"],
                ["im_online", "AccountId"],
                ["authority_discovery", "AccountId"],
                ["parachains", "AccountId"]
            ]
        },
        "Bid": {
            "type": "struct",
            "type_mapping": [
                ["uuid", "u32"],
                ["max_energy", "u32"],
                ["market_uuid", "Option<Vec<u8>>"],
                ["asset_uuid", "Option<Vec<u8>>"],
                ["time_slot", "Vec<u8>"]
            ]
        },
        "Offer": {
            "type": "struct",
            "type_mapping": [
                ["uuid", "u32"],
                ["max_energy", "u32"],
                ["market_uuid", "Option<Vec<u8>>"],
                ["asset_uuid", "Option<Vec<u8>>"],
                ["energy_type", "Vec<u8>"],
                ["time_slot", "Vec<u8>"]
            ]
        },
        "Match": {
            "type": "struct",
            "type_mapping": [
                ["ids", "u32"],
                ["price", "u32"],
                ["energy", "u32"]
            ]
        }
    }
}
```

**Comment by lana-shanghai** [comment]
Aaah, I see now, it was actually working for whatever reason, but it randomly started giving me the good old 
```
Failed to send: {'code': 1002, 'message': 'Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn\\\'t exist" } })', 'data': 'RuntimeApi("Execution failed: ApiError(FailedToConvertParameter { function: \\"validate_transaction\\", parameter: \\"tx\\", error: Error { cause: None, desc: \\"Could not decode `MultiAddress`, variant doesn\\\\\\\'t exist\\" } })")'}
```
Maybe something with the UI. In process of debugging :)

**Comment by lana-shanghai** [comment]
Hey Arjan! Unfortunately it keeps failing with the above error. The UI sends everything fine, but the substrate interface isn't happy with MultiAddress. Any idea in which direction maybe to proceed? :)

**Comment by arjanz** [comment]
Then it seems you are running an older version of Substrate without `MultiAddress` support. What you can try is to change:

```json
...
"Address": "AccountIdAddress",
"LookupSource": "AccountIdAddress",
...
```
