### ISSUE TITLE
Error Method not found in rpc_request

### ISSUE THREAD

**Issue by tubleronchik** [polkascan/py-substrate-interface#123]
Hi Arjan,

I've been trying to create and sign a signed extrinsics using the example from README but got an error while getting account nonce. Here is the error:

```
Traceback (most recent call last):
  File "send_to_datalog.py", line 53, in <module>
    extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
  File "/home/tubleronchik/.local/lib/python3.6/site-packages/substrateinterface/base.py", line 1701, in create_signed_extrinsic
    nonce = self.get_account_nonce(keypair.ss58_address) or 0
  File "/home/tubleronchik/.local/lib/python3.6/site-packages/substrateinterface/base.py", line 1622, in get_account_nonce
    response = self.rpc_request("system_accountNextIndex", [account_address])
  File "/home/tubleronchik/.local/lib/python3.6/site-packages/substrateinterface/base.py", line 531, in rpc_request
    raise SubstrateRequestException(message['error'])
substrateinterface.exceptions.SubstrateRequestException: {'code': -32601, 'message': 'Method not found'}
```
I've noticed, that ```get_account_nonce``` function was changed in v 0.13.7. I've tried on v 0.13.8 and v 0.13.9. Maybe you have any ideas, how can i fix this problem? 
Thank you in advance.

P.S. It seems to be working on v 0.13.6

**Comment by arjanz** [comment]
Which version of Substrate are you using (or which network are you connecting?) It seems it is a somewhat older version of Substrate that doesn't support the RPC method ``. I changed this in https://github.com/polkascan/py-substrate-interface/commit/03501bf565b6e77d1f3dd9b335458236cf95784 to also take transactions in the mempool into account, but I guess I have to make a fallback here in case this isn't available

**Comment by tubleronchik** [comment]
I am using [Robonomics Network](https://parachain.robonomics.network/#/explorer) and there was a problem with its parachains, which actually did not support this method. Will be fixed soon.

Thank you!
