### ISSUE TITLE
get_runtime_events() --> RemainingScaleBytesNotEmptyException

### ISSUE THREAD

**Issue by drandreaskrueger** [polkascan/py-substrate-interface#13]
Playing with your new version, I encountered this little error:
```
block #629 (0xd0ab022ea2a4120a315e20b8649cea4ee4ed653d276aa00594151f2072e6d02d)
Traceback (most recent call last):
  File ".../issue_RemainingScaleBytesNotEmptyException.py", line 21, in <module>
    print(substrate.get_runtime_events(ch))
  File ".../env/lib/python3.7/site-packages/substrateinterface/__init__.py", line 826, in get_runtime_events
    block_hash=block_hash
  File ".../env/lib/python3.7/site-packages/substrateinterface/__init__.py", line 805, in get_runtime_state
    response['result'] = obj.decode()
  File ".../env/lib/python3.7/site-packages/scalecodec/base.py", line 281, in decode
    raise RemainingScaleBytesNotEmptyException('Current offset: {} / length: {}'.format(self.data.offset, self.data.length))

scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 15 / length: 19
```
for both of the last 2 lines in:
```
import substrateinterface
substrate = substrateinterface.SubstrateInterface(url="ws://127.0.0.1:9944/")
ch=substrate.get_chain_head()
chb=substrate.get_chain_block(ch)
chbn=int(chb['block']['header']['number'],16)
print("block #%s (%s)" % (chbn, ch))

print(substrate.get_runtime_events(ch))
print(substrate.get_runtime_events())
```
when run with the `node-template 2.0.0-rc2-83d7157-x86_64-linux-gnu` version of [node-template](https://github.com/substrate-developer-hub/substrate-node-template):

    node-template --dev

Thanks a lot!

P.S.: what are the correct `(address_type, type_registry_preset)` in `SubstrateInterface(url, address_type, type_registry_preset)` for that default `node-template --dev` chain, by the way? Asking because your README.md example chooses `(42, 'kusama')` and I would like to instead of kusama go with that default `node-template --dev` - and I suspect that needs different parameters?

P.P.S.: Nice to have would be:
```
import scalecodec, substrateinterface
print (substrateinterface.__version__, scalecodec.__version__)
```

**Comment by arjanz** [comment]
This should be fixed by the updates on the 'default' type registry in scalecodec version 0.9.54

The version check in code is a nice addition, I'll make an issue for that!

**Comment by drandreaskrueger** [comment]
Great, looks like it's fixed now:

    {'jsonrpc': '2.0', 'result': None, 'id': 1}

thanks a lot. Can close.

P.S.: what are the correct `(address_type, type_registry_preset)` in SubstrateInterface(url, address_type, type_registry_preset) for that default [node-template --dev chain](https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/v2.0.0-rc2). Thanks.

**Comment by drandreaskrueger** [comment]
above was for block 0.

Now this for a later block:

```
block #27 (0xc3f3861acb5b7933ee0c848faff4733ce12d0cd49c95795ff400251c51066a41)
{'id': 1,
 'jsonrpc': '2.0',
 'result': [{'event_id': 'ExtrinsicSuccess',
             'event_idx': 0,
             'extrinsic_idx': 0,
             'module_id': 'System',
             'params': [{'type': 'DispatchInfo',
                         'value': {'class': 'Mandatory',
                                   'paysFee': False,
                                   'weight': 158000000},
                         'valueRaw': ''}],
             'phase': 0,
             'topics': [],
             'type': '0000'}]}
```

**Comment by arjanz** [comment]
The "default" type registry keeps up with latest Substrate, maybe make a separate "node-template" in the future.

**Comment by drandreaskrueger** [comment]
> registry keeps up with latest Substrate, maybe we will make a separate "node-template" in the future.

Are they different?

How?

What do I have to do, to use node-template with your library? 

Thanks.
