### ISSUE TITLE
new version `contract.exec` syntax error

### ISSUE THREAD

**Issue by garrettmaring** [polkascan/py-substrate-interface#133]
previously, i was able to instantiate an ink! contract and call `exec` on it for signed extrinsics. now I receive 'syntax error'

**Comment by arjanz** [comment]
* Did you update to the latest version of `substrate-interface` and `scalecodec`? 
* Which implementation (canvas, substrate, node-template, etc) and runtime_id did you connect to?
* Can you provide a code snippet so I can reproduce the issue?

On the latest canvas-node I didn't ran into any problem, latest substrate (with the new `MetadataV14`) though the test resulted into an `AttributeError` so I will look into that, but it is not the abrupt 'syntax error' you describe.

**Comment by arjanz** [comment]
Can you try https://github.com/polkascan/py-substrate-interface/releases/tag/v1.0.1 to see if this issue is resolved?
