### ISSUE TITLE
SubstrateInterface get_runtime_metadata potential typo

### ISSUE THREAD

**Issue by JacquesBermanWebster** [polkascan/py-substrate-interface#134]
Hello. I think I found a typo in SubstrateInterface class, get_runtime_metadata method.

There is this block of code:
`metadata_decoder = self.runtime_config.create_scale_object(
                'VersionedMetadata', data=ScaleBytes(response.get('result')))`
And I believe it should go like this
`metadata_decoder = self.runtime_config.create_scale_object(
                'MetadataVersioned', data=ScaleBytes(response.get('result')))`

**Comment by arjanz** [comment]
You are absolutely right, thanks for reporting!

**Comment by JacquesBermanWebster** [comment]
You're welcome. Thanks for quick response and fix!
