### ISSUE TITLE
Add support for Ethereum Keypairs 

### ISSUE THREAD

**Issue by hyd628** [polkascan/py-substrate-interface#141]
We would like to use this library with EVM compatible parachains such as Moonbeam, but need support for Ethereum Keypairs to be included.

In this PR to Substrate: https://github.com/paritytech/substrate/pull/8615, the parachain's types will be included in the Substrate metadata, so the types can be obtained at runtime. Thus the only additional change for py-substrate-interface to work with EVM compatible parachains is to add support for Ethereum keypairs (ECDSA) [here](https://github.com/polkascan/py-substrate-interface/blob/3a642c902c74c1824c85e0f4529d511266fa3dea/substrateinterface/base.py#L53).

This would be a good feature to have given the popularity of Pallet EVM and Frontier and the number of parachains that have some compatibility with EVM and Ethereum keypairs.

**Comment by arjanz** [comment]
Support for ECDSA keypairs added in https://github.com/polkascan/py-substrate-interface/releases/tag/v1.1

Feedback would be appreciated..

**Comment by hyd628** [comment]
Awesome. We will try a couple of things with it and let you know.

**Comment by arjanz** [comment]
I received some comments that there was some trouble submitting transactions to Moonbase Alpha testnet. I will look for a way to achieve this a bit more elegant, but for now you can config the lib correctly with:

```python
substrate = SubstrateInterface(
    url=MOONBASE_ALPHA_WS_URL
)
substrate.init_runtime()
substrate.runtime_config.update_type_registry({
    "types": {
        "Address": "H160",
        "LookupSource": "H160",
        "AccountId": "H160",
        "ExtrinsicSignature": "EcdsaSignature",
    }
})
```

**Comment by arjanz** [comment]
@hyd628 Did you ran into any issues? Otherwise I'll close the ticket..

**Comment by hyd628** [comment]
Thanks, the changes look good, but I did run into a few issues:

1. I can't get Keypair.create_from_private_key(privatekey, crypto_type=KeypairType.ED25519) to work, it's throwing this error:

Traceback (most recent call last):
  File "/Users/henryduong/Documents/workspace/pysubstrateinterface/sendtransaction.py", line 29, in <module>
    keypair = Keypair.create_from_private_key(privatekey, crypto_type=KeypairType.ED25519)
  File "/usr/local/lib/python3.9/site-packages/substrateinterface/base.py", line 302, in create_from_private_key
    return cls(
  File "/usr/local/lib/python3.9/site-packages/substrateinterface/base.py", line 100, in __init__
    raise ValueError('No SS58 formatted address or public key provided')
ValueError: No SS58 formatted address or public key provided

create_from_mnemonic works.

2. .create_signed_extrinsic() currently doesn't work with Ethereum style signed transactions, right? getting this error:

File "/Users/henryduong/Documents/workspace/pysubstrateinterface/sendtransaction.py", line 45, in <module>
    extrinsic = moonbeamAPIProvider.create_signed_extrinsic(call=call, keypair=keypair)
  File "/usr/local/lib/python3.9/site-packages/substrateinterface/base.py", line 1535, in create_signed_extrinsic
    nonce = self.get_account_nonce(keypair.ss58_address) or 0
  File "/usr/local/lib/python3.9/site-packages/substrateinterface/base.py", line 1455, in get_account_nonce
    response = self.rpc_request("system_accountNextIndex", [account_address])
  File "/usr/local/lib/python3.9/site-packages/substrateinterface/base.py", line 553, in rpc_request
    raise SubstrateRequestException(message['error'])
substrateinterface.exceptions.SubstrateRequestException: {'code': -32602, 'message': 'Invalid params: 0x prefix is missing.'}

Here is the test script I used:

https://github.com/hyd628/pysubstrateinterface/blob/main/sendtransaction.py

**Comment by arjanz** [comment]
@hyd628 I think you made a typo when chosing the `crypto_type` (should be`KeypairType.ECDSA`) .. I replaced it with:
```python
keypair = Keypair.create_from_private_key(privatekey, crypto_type=KeypairType.ECDSA)
```
And it seems to work with the test script you provided. Could you confirm this?

The feedback you got was not great, I'll improve this so this will be easier to debug.

**Comment by arjanz** [comment]
> 2\. .create_signed_extrinsic() currently doesn't work with Ethereum style signed transactions, right?

This should also work with Ethereum (Ecdsa) signatures

**Comment by hyd628** [comment]
Everything seems to be working now, thanks this is great!
