### ISSUE TITLE
Format of the timestamp in timestamp extrinsic?

### ISSUE THREAD

**Issue by stolpa4** [polkascan/py-substrate-interface#144]
Hello, I found that for recent blocks (polkadot) the timestamp extrinsic is parsed with `extrinsic['call']['call_args']['type'] == 'Moment'` and value is some rather big number (e.g. for block 7313001 it is 1634560404001) - clearly it is not a Unix timestamp. How can I parse this number into timestamp? 

I've used to parse timestamp values as strings in format `'%Y-%m-%dT%H:%M:%S.%f'`, but it worker for timestamps with `extrinsic['call']['call_args']['type'] == 'Compact<Moment>'`.

Now when the call value is integer, I need to introduce some changes to my code, but I can't find what format the timestamp value is.

**Comment by stolpa4** [comment]
@maayank Thanks!

**Comment by arjanz** [comment]
After some discussion how to deal with the `Moment` type it will be consistently treated as an `u64` as per the Substrate codebase, also for pre-MetadataV14 runtimes. Conversion to e.g. a datetime will be up to the application.
