### ISSUE TITLE
Support the new `metadata.json` format from ink! 3.0.0-rc6

### ISSUE THREAD

**Issue by garrettmaring** [polkascan/py-substrate-interface#147]
I've opened an issue against `ink!` though this is likely just an update needed to py-substrate-interface to support changing metadata.json formats.

If generating ink! metadata for a contract with 3.0.0-rc6, py-substrate-interface will fail to parse types (as it's a differently formatted file) and other json fields.

**Comment by garrettmaring** [comment]
Very exciting to see this merged so quickly, @arjanz! Is there a new release available via _pip_?

**Comment by arjanz** [comment]
Yes the PR is released https://pypi.org/project/substrate-interface/1.0.6/, added more unit tests and tested with several contacts, so please let me know if this works for you.
