### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by wjy19990622** [polkascan/py-substrate-interface#15]

**Comment by wjy19990622** [comment]
i use the command  "pip install substrate-interface" ,
and my code for example:
```
from substrateinterface import SubstrateInterface, SubstrateRequestException
substrate = SubstrateInterface(
    url="wss://kusama-rpc.polkadot.io/",
    address_type=2,
    type_registry_preset='kusama'
)

substrate.get_chain_head()
```

**Comment by wjy19990622** [comment]
i ensure that the asyncio is unique in my project and  my python site-packages.

**Comment by arjanz** [comment]
I suspect this is because of incompatibility with Python 3.6 and asyncio.run which was introduced in 3.7. Are you able to upgrade to Python 3.7+?
