### ISSUE TITLE
Filter the event in blocks

### ISSUE THREAD

**Issue by kernel1983** [polkascan/py-substrate-interface#155]
Does py-substrate-interface support filter the event with the block range?
Or does it depends on the substrate?

In web3.py we can do 

    f = contract.events.MyEvent.createFilter(fromBlock='0x0')
    for i in w3.eth.get_logs(f.filter_params):
        print(i)

But in py-substrate-interface I can only check the blocks one by one.

**Comment by arjanz** [comment]
py-substrate-interface is limited by what the RPC of a Substrate node can provide, and filtering events is not possible. You will need a third party indexing service, I believe Subscan provides one.
