### ISSUE TITLE
Get block caching

### ISSUE THREAD

**Issue by stolpa4** [polkascan/py-substrate-interface#158]
Hello, it seems to me that caching `get_block` function can get broken, because in some cases this function may return `None` (e.g. when the block is not found, like here: https://github.com/polkascan/py-substrate-interface/blob/eb9e75fba473011e2b749fd972f6a1bf2207e0e7/substrateinterface/base.py#L2223-L2226). So once you have not found the block, there's no way to retry, as this `None` value is cached. We should do something with it.

**Comment by arjanz** [comment]
You mean when the node is not in sync yet or after a reorg? That is indeed undesirable, what I will try first is to never cache when `None` is returned. If that still doesn't work I will disable cache all together, as it does then more harm than good

**Comment by arjanz** [comment]
Caching is removed in latest release
