### ISSUE TITLE
Examining extrinsic one by one in a batch extrinsic

### ISSUE THREAD

**Issue by AmirAhrari** [polkascan/py-substrate-interface#160]
Can you tell me how to check extrinsics in utility.batch extrinsics one by one to see if they succeeded or failed?

**Comment by arjanz** [comment]
You can check the `Utility.ItemCompleted` event to keep progress when a call (semantics, but extrinsic is only the vehicle containing the actual call, and a `Utility.batch` extrinsic can contain multiple calls) is completed .

**Comment by AmirAhrari** [comment]
Thanks for your help!
