### ISSUE TITLE
{'code': 1012, 'message': 'Transaction is temporarily banned'}

### ISSUE THREAD

**Issue by DanielMS93** [polkascan/py-substrate-interface#161]
Do you have any advice on how to diagnose and fix this type of issue?

The error has been raised on a transaction that has completed successfully on every other occasion.

Is this a network issue? if so, do we know what causes it?

Is this a transaction level issue? If so, how should i go about resolving this? can i cancel the old and create a new transaction? what is the best way to do this with the py-substrate-interface api

**Comment by arjanz** [comment]
You will have to catch `SubstrateRequestException` and analyse why it failed, if you just retry I can result in a ban.
