### ISSUE TITLE
NotImplementedError: Decoder class for "Address" not found

### ISSUE THREAD

**Issue by gilmouta** [polkascan/py-substrate-interface#166]
When using SubstrateInterface with Moonriver, I am getting the following error when creating a signed extrinsic:
`NotImplementedError: Decoder class for "Address" not found`
The exact same code works for Moonbase Alpha (Moonriver's test network), which is running on the same runtime (both include MetadataV14). 
I am initializing the SubstrateInterface using only the RPC URL.

**Comment by arjanz** [comment]
Fix released in https://github.com/polkascan/py-substrate-interface/releases/tag/v1.1.4
