### ISSUE TITLE
How to disable an option in storage query

### ISSUE THREAD

**Issue by johnuopini** [polkascan/py-substrate-interface#167]
When using "Substrate Portal" storage query i can disable optional parameters using a toggle called "Include Option", which allows me to call a method without a parameter when optional. I cannot reproduce the same using this interface, there is no way to provide None as an argument or disable an option.

**Comment by arjanz** [comment]
Have you tried the query_map() function?

**Comment by johnuopini** [comment]
> Have you tried the query_map() function?

That was it! Thanks!
