### ISSUE TITLE
Support for contracts metadata V2

### ISSUE THREAD

**Issue by arjanz** [polkascan/py-substrate-interface#168]
https://github.com/polkadot-js/api/pull/4289

**Comment by cmichi** [comment]
Hi there, I just want to point out that there is also a metadata V3 now. You can find the (two) changes for V3 described here: https://github.com/paritytech/ink/blob/master/RELEASES.md#metadata-changes.

For V2 there are some more details found here: https://github.com/paritytech/ink/blob/master/RELEASES.md#new-metadata-format.

**Comment by arjanz** [comment]
Thanks for pointing this out @cmichi, it is still on the todo list, mainly because back then I couldn't find a suitable test node to test this against.. Do you know if there is a branch or fork of Substrate where I can test V2 (and perhaps also V3)?

**Comment by arjanz** [comment]
Ok I obviously didn't read your release notes thoroughly enough.. :) I just successfully created a V3 contract with the latest `cargo-contract` CLI  and deployed on `substrate-contracts-node` `v0.5.0`. So I have my test env for V3, which is great. I'll bump this in my todo-list

**Comment by cmichi** [comment]
Ah nice, that's great to hear!

Not sure if you know, but there are binary releases available for `substrate-contracts-node` on [the releases page](https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.5.0). This might help you if you only need to do some basic testing and don't want to wait for the entire compilation to go through ;-).

We also have a [testnet](https://github.com/paritytech/canvas#rococo-deployment), which could come in handy if you need an up-to-date endpoint ([here's the polkadot-js link to it](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-canvas-rpc.polkadot.io#/explorer)).
