### ISSUE TITLE
how to parse transaction from block

### ISSUE THREAD

**Issue by zhenghq** [polkascan/py-substrate-interface#17]
how to parse transaction from block, pls help me!

**Comment by arjanz** [comment]
Could you provide some more details what is not working for you?

Have you tried the example code provided here : https://github.com/polkascan/py-substrate-interface#get-extrinsics-for-a-certain-block ?

**Comment by zhenghq** [comment]
> Could you provide some more details what is not working for you?
> 
> Have you tried the example code provided here : https://github.com/polkascan/py-substrate-interface#get-extrinsics-for-a-certain-block ?

thank you!  
by the way, how to get Validators informations from block?
