### ISSUE TITLE
ValueError: Storage function map requires 1 parameters, 0 given

### ISSUE THREAD

**Issue by wowvwow** [polkascan/py-substrate-interface#170]
![image](https://user-images.githubusercontent.com/28591822/146635311-9bc5c0f0-b314-41a4-87a4-d1be157742fb.png)

substrateinterface： 1.1.4

user_staker_info = self.substrate.query_map(
  File "/usr/local/lib/python3.8/dist-packages/substrateinterface/base.py", line 1118, in query_map
    raise ValueError(f'Storage function map requires {len(param_types) -1} parameters, {len(params)} given')
ValueError: Storage function map requires 1 parameters, 0 given

**Comment by arjanz** [comment]
Some issue as https://github.com/polkascan/py-substrate-interface/issues/169#issuecomment-997196690

**Comment by arjanz** [comment]
See https://github.com/polkascan/py-substrate-interface/issues/169#issuecomment-1000800101

**Comment by wowvwow** [comment]
ok, ty u, I checked it, and It works great
