### ISSUE TITLE
Conflicting version in requirements graph for eth-typing

### ISSUE THREAD

**Issue by maayank** [polkascan/py-substrate-interface#174]
Hey @arjanz ,
My project uses pipenv for package management and I get this error when trying to update to the latest substrate-interface:
```
There are incompatible versions in the resolved dependencies:
  eth-typing<3.0.0,>=2.2.1 (from eth-utils==1.10.0->substrate-interface==1.1.6->-r /tmp/pipenvn7q5cvd_requirements/pipenv-mq4ozh93-constraints.txt (line 12))
  eth-typing<4,>=3.0.0 (from eth-keys==0.4.0->substrate-interface==1.1.6->-r /tmp/pipenvn7q5cvd_requirements/pipenv-mq4ozh93-constraints.txt (line 12))
```

As you can see, different packages require exclusive version of 'eth-typing' (<3, >=3). What do you suggest?

**Comment by arjanz** [comment]
The conflict is between packages `eth-utils` and `eth-keys`, which do not have an overlapping version requirement. What I can try is loosen the version requirement of these two package and hope it resolves. 

Interesting is that I don't have this error, are you using the new pip conflict resolution strategy?

**Comment by arjanz** [comment]
I tested several versions of `eth_utils` and `eth-keys` and made the version requirement less strict, I think it shouldn't be a problem anymore, you can test by installing Github master if this works for you, then it will be included in next release.

**Comment by nsagie8** [comment]
@arjanz 
Hi,
I'm working with @maayank
It should be good for us, and we would like you to include it in next release.

Thanks

**Comment by maayank** [comment]
Solved with the latest release, thanks @arjanz !
