### ISSUE TITLE
Polkadot. js createFromJson function corresponds to which python SDK function?

### ISSUE THREAD

**Issue by 99Kies** [polkascan/py-substrate-interface#178]
And unlock methods

**Comment by arjanz** [comment]
I'm not familiar with all functionality of Polkadot.js, so you have to give more context what exactly your question is..

**Comment by 99Kies** [comment]
<https://github.com/polkadot-js/common/blob/master/packages/keyring/src/pair/decode.ts>
Decryption of Pkcs8

**Comment by 99Kies** [comment]
@arjanz  In fact, it is about Pksc8 decryption.

**Comment by 99Kies** [comment]
We need this to implement the `createFromJson` method in the JS library.

**Comment by arjanz** [comment]
And of course a PR to get me a head start is always appreciated :)

**Comment by 99Kies** [comment]
> And of course a PR to get me a head start is always appreciated :)

I think this is very important, so i suggest setting this issue as TODO

**Comment by arjanz** [comment]
> > And of course a PR to get me a head start is always appreciated :)
> 
> I think this is very important, so i suggest setting this issue as TODO

Well to you maybe, but I think other things are more important at the moment. If you don't like that, you can always contribute it yourself. Good luck.

**Comment by arjanz** [comment]
Functionality released in https://github.com/polkascan/py-substrate-interface/releases/tag/v1.3.4
