### ISSUE TITLE
Provide a way to decode Ethereum.transaction extrinsic (Moonbeam/Moonriver)

### ISSUE THREAD

**Issue by johnuopini** [polkascan/py-substrate-interface#179]
I see Polkadot.JS Ethereum.transactions are correctly displaying method called within the EVM and parameters, i guess this is using solidity to decode them, would be nice to have an example or direct support for this.

**Comment by arjanz** [comment]
Can you explain more what you mean and where you saw this? 

I see the output of an `ethereum.transact` extrinsic is more or less the same as I see on Polkadot.JS apps (example: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbeam.network#/explorer/query/0xdf4ff0dc0dafdf9f131c4f19c6e5c6c944d801ed3b98e7a8396ac750733a5633)

**Comment by johnuopini** [comment]
I thought moonriver was using a different format, you are right, I am trying to understand how to decode the signer, the arguments and then parse single events. I see Polkascan provides signer address and events decoded how is that done?

**Comment by johnuopini** [comment]
Sorry i just realized i can just parse the event, by bad!
