### ISSUE TITLE
'call' must be of type Call

### ISSUE THREAD

**Issue by wjy19990622** [polkascan/py-substrate-interface#19]
Traceback (most recent call last):
  File "/home/wjy/桌面/Transx_Gitlab正式版本/transx/transx/target/release/test.py", line 33, in <module>
    extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
  File "/home/wjy/桌面/ENV/lib/python3.7/site-packages/substrateinterface/__init__.py", line 960, in create_signed_extrinsic
    raise TypeError("'call' must be of type Call")
TypeError: 'call' must be of type Call
<class 'scalecodec.types.GenericCall'>

there are my code:
```
substrate = SubstrateInterface(
    url="ws://47.108.199.133:9945",
    address_type=42,
    type_registry_preset='default'
)
mnemonic = Keypair.generate_mnemonic()

keypair = Keypair.create_from_mnemonic(mnemonic, 2)

print("Created address: {}".format(keypair.ss58_address))
call = substrate.compose_call(
    call_module='Balances',
    call_function='transfer',
    call_params={
        'dest': '5GnGKSCitk1QPpMNugtTGX9t6TqzDGvL5BqKzLfHNsLSrwqN',
        'value': 100 * 10**14
    }
)
```

**Comment by arjanz** [comment]
I was able to execute your example using latest release (v0.9.17). There were changes on this subject recently though, did you upgrade to the latest release of `py-substrate-interface`?
