### ISSUE TITLE
Events not correctly fetched in receipt

### ISSUE THREAD

**Issue by johnuopini** [polkascan/py-substrate-interface#194]
I am trying to get events in this extrinsic:
https://moonbeam.subscan.io/extrinsic/413415-0

I do this by using:
```substrate.retrieve_extrinsic_by_identifier("413415-0")```

Problem is that result has just one event and not hundreds like the one in Subscan.
Is this a library limitation?

**Comment by johnuopini** [comment]
You are right, those are not related to the extrinsic but to the block itself, JS lists them inside the "System events" for the block, does the library support fetching block level events?

**Comment by arjanz** [comment]
You can retrieve all the events for a block with: 

`events = substrate.get_events(block_hash="0x88f5fb3ff6384c127d16408dcfad626fe63081a856c303bf3423b5421a2ced65")`

**Comment by johnuopini** [comment]
Found that, great stuff!!!
