### ISSUE TITLE
Multi-language bip39 mnemonic support

### ISSUE THREAD

**Issue by vtexier** [polkascan/py-substrate-interface#197]
Last version v0.1.9 of [py-bip39-bindings](https://github.com/polkascan/py-bip39-bindings) now support multi-language for bip39 mnemonics.

Could it be possible to support it also in this API ?

I can try to propose a PR if it helps.

**Comment by arjanz** [comment]
You are fast, I released this an hour ago :) (and still need to compile the `aarch64` wheels)

But sure, any help would be appreciated

**Comment by vtexier** [comment]
You were faster than me! Sorry, I was on holidays.

**Comment by arjanz** [comment]
No sweat, I'm sure there will be more opportunities to contribute in the future :)

**Comment by vtexier** [comment]
Oops.There is an error in the comments. Japanese language code "**jap**" raise an error. Code "**ja**" works fine.
So Japanese language code should be "**ja**".

**Comment by arjanz** [comment]
Indeed.. sharp observation, fixed! I will make a new release probably somewhere end of the week

**Comment by vtexier** [comment]
To help on language selection, may be we should had a MnemonicLanguageCode class with predefined constants like KeypairType. If you are Ok with that, I will make a PR.

**Comment by arjanz** [comment]
Yes that sounds like a good idea!
