### ISSUE TITLE
(FR) let the function do the xxhash'ing of the storage key name

### ISSUE THREAD

**Issue by drandreaskrueger** [polkascan/py-substrate-interface#2]
Hi! I am trying out your library. Very nice, that should save me time.

Without unittests, however it _took_ time to get this one working:

    get_storage_by_key (block_hash, storage_key)

In the end, I managed:

    get_storage_by_key(storage_key='0x50a63a871aced22e88ee6466fe5aa5d9', block_hash=0x454...)

> '0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d'

which is [the result from Shawn's tutorial](https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/#storage-value-query).

My feature request:

    get_storage_by_key (block_hash, storage_key_name='Sudo Key')

and then the `xxh6464('Sudo Key')` is done _within_ that function.

thanks for considering it.

**Comment by drandreaskrueger** [comment]
Like this?

https://github.com/polkascan/py-substrate-interface/pull/4/

**Comment by emielvanderhoek** [comment]
Hi @drandreaskrueger 

Yeah thank you. We won't be merging that.
We are working on a generalized solution for exactly this.
You can find the spec here: https://github.com/w3f/Web3-collaboration/blob/master/grants/speculative/python_substrate_api.md

We hope to finish that by the end of the year.
Therefore, I am closing this issue.
