### ISSUE TITLE
String Decimals Being Returned in Substrate Error Handling

### ISSUE THREAD

**Issue by kristian1108** [polkascan/py-substrate-interface#211]
In the Westend runtime, error codes are bring returned as string decimals on occasion which is breaking the provided error parsing logic. 

See question and answer in the Substrate stack exchange: https://substrate.stackexchange.com/questions/1972/0x02000000-being-returned-in-extrinsic-receipt-and-failing-error-module-indexing

**Comment by arjanz** [comment]
This is indeed caused by recently released PR https://github.com/paritytech/substrate/pull/10242, the change in error message format needs to implemented in the lib as well, I'll follow up on this

**Comment by arjanz** [comment]
Fix released in https://github.com/polkascan/py-substrate-interface/releases/tag/v1.2.4
