### ISSUE TITLE
Keypair sign returns bytes, not string

### ISSUE THREAD

**Issue by Maharacha** [polkascan/py-substrate-interface#215]
https://github.com/polkascan/py-substrate-interface/blob/5119bcf87f9a07e570f0c5e9c1bedddf1db1d1fd/substrateinterface/base.py#L354
Sign method return bytes, but the docstring says `string`.

I noticed this because https://github.com/polkascan/py-substrate-interface/blob/5119bcf87f9a07e570f0c5e9c1bedddf1db1d1fd/substrateinterface/base.py#L1755 requires `string`.
So to make it work I have to convert the signature to hex string before creating the extrinsic, `signature.hex()`

I did not have to do this before, not sure when it started to fail though...

**Comment by arjanz** [comment]
The docstring is indeed outdated, it was changed to the more native representation `bytes`. And it is not very intuitive to convert it first to be able to use it for `create_signed_extrinsic()`, for backwards compatibility sake I will convert the type to a `Union[str, bytes]` so both types can be used and internally converted.

**Comment by Maharacha** [comment]
> The docstring is indeed outdated, it was changed to the more native representation `bytes`. And it is not very intuitive to convert it first to be able to use it for `create_signed_extrinsic()`, for backwards compatibility sake I will convert the type to a `Union[str, bytes]` so both types can be used and internally converted.
> 
> Just like in:
> 
> https://github.com/polkascan/py-substrate-interface/blob/a5418355a66cacbe2340bd1de00f4bf759d61788/substrateinterface/base.py#L381
> 
> )

Sounds great!
