### ISSUE TITLE
py-substrate-interface wheels for aarch64 and armv7

### ISSUE THREAD

**Issue by PaTara43** [polkascan/py-substrate-interface#225]
Hello, 

Would you kindly add pre-built wheels for this library and its dependencies (I've created separate issues  https://github.com/polkascan/py-bip39-bindings/issues/8, https://github.com/polkascan/py-sr25519-bindings/issues/7 and https://github.com/polkascan/py-ed25519-bindings/issues/5) for `aarch64` (RPi 4) and `armv7` (RPi 3) to avoid installing Rust and building library from source (quite time-consuming on RPi's)?

Regards

**Comment by arjanz** [comment]
Hi @PaTara43, there should be `aarch64` support already for those bindings (built on a RPi4): https://pypi.org/project/py-sr25519-bindings/#files https://pypi.org/project/py-ed25519-bindings/#files and https://pypi.org/project/py-bip39-bindings/#files  Could you confirm these are working for you?

As for `armv7`, I don't have a RPi3 and timeboxed this but was unsuccessfully able to find either a hosted runner or VM to make the build.. Maybe you have some pointers for me how to set this up if you have more experience with this?

**Comment by PaTara43** [comment]
I'll come back with confirmation, as far as I understood, no need for dedicated wheels for this  (`py-substrate-interface`) library, right? Those `none-any.whl` are fine.

About the `armv7`, I'll ask my colleagues, I think they did this one day.

**Comment by PaTara43** [comment]
`aarch64` confirmed, sorry for a false alarm.
As for `armv7` I think it is possible for us to build wheels and pass them to you somehow. We have an RPi3

**Comment by arjanz** [comment]
> `aarch64` confirmed, sorry for a false alarm. 
Ok nice, I wasn't sure because although `py-substrate-interface` doesn't require dedicated wheels, I wasn't sure for some other third-party dependencies.

>As for `armv7` I think it is possible for us to build wheels and pass them to you somehow. We have an RPi3
Ok that would be great, yesterday I stumbled upon a RPi3-as-a-service I also gonna check out

**Comment by arjanz** [comment]
Ok I found a hosted RPi3 where was able to build the wheels. Uploaded them to PyPI just now, are these working for you?

**Comment by PaTara43** [comment]
Sorry, I missed your message:(
We are going to find one and test, thanks!
