### ISSUE TITLE
historical TotalIssuance 

### ISSUE THREAD

**Issue by colossus-digital** [polkascan/py-substrate-interface#228]
hi guys, is there a way to get the TotalIssuance value at a given era or block number/hash ?

tnks
A.

**Comment by arjanz** [comment]
For a certain block hash you can use:

```python
total_issuance = substrate.query("Balances", "TotalIssuance", block_hash="0x11a4a00cfb10aa94884afc79d31b34bb212017449748a7a130d8015108a55cb4")
print(total_issuance.value)
```

**Comment by colossus-digital** [comment]
wow, great , thank you very much
last question, how i can get the start block number (or hash) for a given era ?
