### ISSUE TITLE
Mortal extrinsic

### ISSUE THREAD

**Issue by SeungJaeYi** [polkascan/py-substrate-interface#24]
I want to use the era field on extrinsic. Could you update the feature? plz
https://github.com/polkascan/py-substrate-interface/blob/0f5c62e25b289983ee835afc6c53c3867a6c4156/substrateinterface/__init__.py#L969

**Comment by arjanz** [comment]
This is indeed a desirable feature. There has been work done recently to implement mortal eras in scalecoded (https://github.com/polkascan/py-scale-codec/commit/3b3ccd0adba67415dda99736fb5da2c797dd1982) and will have our attention soon.
