### ISSUE TITLE
Add info whether an extrinsic is signed or not

### ISSUE THREAD

**Issue by pranaydotparity** [polkascan/py-substrate-interface#244]
Hey everyone,
Can a field be added to the extrinsic data that would show if the extrinsic has been signed or not?
As far as I'm aware this information is not available in the extrinsic data at the moment.

**Comment by arjanz** [comment]
Have you tried `extrinsic.signed` of the `GenericExtrinsic` object?

**Comment by pranaydotparity** [comment]
I checked it just now, Thanks for pointing it out. :)
This is what I was looking for.
