### ISSUE TITLE
Error parsing (some) blocks on Acala

### ISSUE THREAD

**Issue by KarimJedda** [polkascan/py-substrate-interface#256]
There are errors on some of the Acala blocks (happens every now and then):

```
from substrateinterface import SubstrateInterface

substrate = SubstrateInterface(
    url="wss://acala-rpc-2.aca-api.network/ws"
)

BLOCK_ID = 2112493
block = substrate.get_block(block_number=BLOCK_ID)

```
Returns:
`ValueError: Index '3' not present in Enum type mapping` 

Any hint what it could be? It looks like it's something in `py-scale-codec` that is erroring out. 

Versions:
substrate-interface==1.3.2
scalecodec==1.0.43

Thank you very much :)

**Comment by arjanz** [comment]
It seems Acala uses a new type of signature unknown to the library, current known curves are [Ed25519 (0), Sr25519 (1) and Ecdsa (2)](https://github.com/polkascan/py-scale-codec/blob/a12c199c69ea80f49a2fb2771752a9741e0fe26d/scalecodec/type_registry/metadata_types.json#L1557)

**Comment by arjanz** [comment]
Ok Acala has an extended set of signatures, as defined here: https://github.com/AcalaNetwork/bodhi.js/blob/0f75a1c6aedd2fa5bcc36a2c18636ed4bbbb1fad/eth-providers/src/chain-api.ts#L29

I'll add definition this in scalecodec

**Comment by KarimJedda** [comment]
Oh wow, thank you very much for the quick addition! I'll update the services on our end right away. 👍
