### ISSUE TITLE
compose_class function causes raise TypeError("'call' must be of type Call")

### ISSUE THREAD

**Issue by lana-shanghai** [polkascan/py-substrate-interface#26]
I suggest to change the class name check in the substrateinterface __init.py__ file. The current code is:

`     # Check requirements
        if call.__class__.__name__ != 'Call':
            raise TypeError("'call' must be of type Call")`

but in the scalecodec module the file types.py has this definition: 

`class GenericCall(ScaleType):`

changing the __init.py__ file to 

`  # Check requirements
        if call.__class__.__name__ != 'GenericCall':
            raise TypeError("'call' must be of type GenericCall")`

solves the error. Shall I do a PR? There was another guy complaining about this earlier in the issues.

**Comment by jacklcz** [comment]
> I suggest to change the class name check in the substrateinterface **init.py** file. The current code is:
> 
> ` # Check requirements if call.__class__.__name__ != 'Call': raise TypeError("'call' must be of type Call")`
> 
> but in the scalecodec module the file types.py has this definition:
> 
> `class GenericCall(ScaleType):`
> 
> changing the **init.py** file to
> 
> ` # Check requirements if call.__class__.__name__ != 'GenericCall': raise TypeError("'call' must be of type GenericCall")`
> 
> solves the error. Shall I do a PR? There was another guy complaining about this earlier in the issues.

Yes, I've met the question as you too，I change the init.py to GenericCall, it works

**Comment by jacklcz** [comment]
> > I suggest to change the class name check in the substrateinterface **init.py** file. The current code is:
> > ` # Check requirements if call.__class__.__name__ != 'Call': raise TypeError("'call' must be of type Call")`
> > but in the scalecodec module the file types.py has this definition:
> > `class GenericCall(ScaleType):`
> > changing the **init.py** file to
> > ` # Check requirements if call.__class__.__name__ != 'GenericCall': raise TypeError("'call' must be of type GenericCall")`
> > solves the error. Shall I do a PR? There was another guy complaining about this earlier in the issues.
> 
> Yes, I've met the question as you too，I change the init.py to GenericCall, it works

兄弟，突然发现我们是一国的，能透露个邮箱加个微信不？？

**Comment by lana-shanghai** [comment]
> > Yes, I've met the question as you too，I change the init.py to GenericCall, it works
> 
> 兄弟，突然发现我们是一国的，能透露个邮箱加个微信不？？

哈哈不是兄弟，我是姐妹！我在上海住了一年。

**Comment by jacklcz** [comment]
> > > Yes, I've met the question as you too，I change the init.py to GenericCall, it works
> > 
> > 
> > 兄弟，突然发现我们是一国的，能透露个邮箱加个微信不？？
> 
> 哈哈不是兄弟，我是姐妹！我在上海住了一年。

哈哈，我邮箱profile就有，可以的话可以加下呢

**Comment by lana-shanghai** [comment]
> 哈哈，我邮箱profile就有，可以的话可以加下呢

我的微信是sveton

**Comment by arjanz** [comment]
> I suggest to change the class name check in the substrateinterface **init.py** file. The current code is:
> 
> ` # Check requirements if call.__class__.__name__ != 'Call': raise TypeError("'call' must be of type Call")`
> 
> but in the scalecodec module the file types.py has this definition:
> 
> `class GenericCall(ScaleType):`
> 
> changing the **init.py** file to
> 
> ` # Check requirements if call.__class__.__name__ != 'GenericCall': raise TypeError("'call' must be of type GenericCall")`
> 
> solves the error. Shall I do a PR? There was another guy complaining about this earlier in the issues.

This issue should actually be fixed since version 0.9.17 (https://github.com/polkascan/py-substrate-interface/commit/0f5c62e25b289983ee835afc6c53c3867a6c4156) Could you guys verify by upgrading? Or is this still an issue in the latest version?

而且我看得懂你们的话，我以前在中国工作了，所以我会说一点点 :) 我可以加你们的微信吗？
