### ISSUE TITLE
Kulupu decode Error 

### ISSUE THREAD

**Issue by jacklcz** [polkascan/py-substrate-interface#27]
kulupu
substrate.get_runtime_block 176637 or 176638 

error info:

raise ValueError("Index '{}' not present in Enum type mapping".format(self.index))
ValueError: Index '8' not present in Enum type mapping

**Comment by arjanz** [comment]
Are you sure you upgraded your libraries to the latest version? Maybe your version of scalecodec didn't get updated, can you try: `pip install scalecodec --upgrade` and try again?

**Comment by jacklcz** [comment]
yes, i'm sure, my scalecodec version is:0.10.14

**Comment by arjanz** [comment]
Could you try the following code snippet, because this is working for me:

```
substrate = SubstrateInterface(
    url="wss://rpc.kulupu.corepaper.org/ws",
    address_type=16,
    type_registry_preset='kulupu'
)


print(substrate.get_runtime_block(block_id=176637))
```

**Comment by jacklcz** [comment]
> Could you try the following code snippet, because this is working for me:
> 
> ```
> substrate = SubstrateInterface(
>     url="wss://rpc.kulupu.corepaper.org/ws",
>     address_type=16,
>     type_registry_preset='kulupu'
> )
> 
> 
> print(substrate.get_runtime_block(block_id=176637))
> ```

thank you very much！
