### ISSUE TITLE
Failed to send

### ISSUE THREAD

**Issue by oggy95** [polkascan/py-substrate-interface#28]
Try to create and send signed extrinsic using example in readme with modification to using polkadot mainnet:

```
from substrateinterface import SubstrateInterface, SubstrateRequestException, Keypair

substrate = SubstrateInterface(url="ws://127.0.0.1:9944", address_type=0)

keypair = Keypair.create_from_mnemonic(MY_MNEMONIC, address_type=0)

call = substrate.compose_call(
    call_module='Balances',
    call_function='transfer',
    call_params={
        'dest': DEST_ACCOUNT
        'value': AMOUNT * 10**10
    }
)

extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)

try:
    result = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)
    print("Extrinsic '{}' sent and included in block '{}'".format(result['extrinsic_hash'], result['block_hash']))

except SubstrateRequestException as e:
    print("Failed to send: {}".format(e))
```

But got an error:

`Failed to send: {'code': 1002, 'message': 'Verification Error: Execution: Trap: Trap { kind: Unreachable }', 'data': 'RuntimeApi("Execution: Trap: Trap { kind: Unreachable }")'}`

**Comment by arjanz** [comment]
I tried your example and works for me when using the public Polkadot node (wss://rpc.polkadot.io). Perhaps there is a connectivity problem with your node, e.g. are you sure it can reach peers through your firewall?

**Comment by oggy95** [comment]
Open firewall, same errors at my own node and public node.

**Comment by arjanz** [comment]
I see the problem, you didn't specify the `type_registry`:

```
substrate = SubstrateInterface(
    url="wss://rpc.polkadot.io",
    address_type=0,
    type_registry_preset='polkadot'
)
```

As habit I guess I automatically added this when I was testing

**Comment by oggy95** [comment]
@arjanz Yes, this working! Thank you!
