### ISSUE TITLE
How to pass the wasm file and abi to contracts.putCode and contracts.instantiate?

### ISSUE THREAD

**Issue by lana-shanghai** [polkascan/py-substrate-interface#29]
How can we pass wasm and abi files? 

An example when I try to instantiate: 

```fh = open('./dummy_erc20/target/erc20.wasm', 'rb').read()
call = substrate.compose_call(
    call_module='Contracts',
    call_function='instantiate',
    call_params={
        'endowment': 100000000000000000,
        'code_hash': '0x238914d69cec97bb70fcf61b30827fcc9edccb13d76d6eeec8e54efb0560f438',
        'gas_limit': 1000000000000,
        'data': fh.hex()
    }
)
```

The above code hash I got from manually uploading the wasm and abi through the UI. 

Also I'd like to know how to pass the bytes to 'data' in `Contracts.putCode`. 
Thanks!

**Comment by arjanz** [comment]
Could you provide the contract WASM and JSON ABI file? Then I can run some tests locally for you

**Comment by lana-shanghai** [comment]
> Could you provide the contract WASM and JSON ABI file? Then I can run some tests locally for you

That's very kind of you - I have added the files here https://github.com/lana-shanghai/python-cli-substrate/tree/master/dummy_erc20 
You need the erc20.wasm and the metadata.json. 
It's not the original erc20 template, but with some extra functions, but I have tested deployment with the polkadot UI and it all works. 
Let me know how it goes and if there is the right way to feed the files to the substrate call. Thank you!

**Comment by lana-shanghai** [comment]
> Could you provide the contract WASM and JSON ABI file? Then I can run some tests locally for you

Hey Arjan, any news? Is it doable? I'd like to be able to deploy a contract directly through the code, not just manually every time (which works for now). Thanks :)

**Comment by arjanz** [comment]
I run some tests, but unfortunately it doesn't work out of the box (yet). When I send a signed extrinsic  for `Contracts.put_code` with the call arg `code` (which should be correct according to the metadata) it returns the following error:

```python
{'code': 1002, 'message': 'Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature', 'data': 'RuntimeApi("Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")'}
```

I suspect for there has to custom encoding for the `Contracts` pallet, but at this point not really sure. I (or somebody else :) ) will have to look into how Polkadot-JS does this.

I used the follow code:

```python
import os

from substrateinterface import SubstrateInterface, SubstrateRequestException, Keypair

substrate = SubstrateInterface(
    url="ws://127.0.0.1:9944",
    address_type=42,
    type_registry_preset='substrate-node-template',
)

mnemonic = '<enter secret words>'

keypair = Keypair.create_from_mnemonic(mnemonic, address_type=42)

balance_info = substrate.get_runtime_state(
    module='System',
    storage_function='Account',
    params=[keypair.ss58_address],
).get('result')

print('Balance info', balance_info)

path = os.path.join(os.path.dirname(__file__), 'erc20.wasm')
with open(os.path.abspath(path), 'rb') as fp:
    code_bytes = fp.read()


call = substrate.compose_call(
    call_module='Contracts',
    call_function='put_code',
    call_params={
        'code': '0x{}'.format(code_bytes.hex())
    }
)

extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)

try:
    result = substrate.submit_extrinsic(extrinsic)

    print('Extrinsic "{}" included in block "{}"'.format(
        result['extrinsic_hash'], result.get('block_hash')
    ))

except SubstrateRequestException as e:
    print("Failed to send: {}".format(e))

```

Also it's not clear for me at this point what the `data` args of  `Contracts.instantiate` should contain, any further info or PR will be appreciated, as for the short term it's not the highest priority to spend a lot of time on this pallet.

**Comment by arjanz** [comment]
Related issue: https://github.com/polkascan/py-substrate-interface/issues/49

**Comment by arjanz** [comment]
There was an issue with generating correct signatures with extrinsics > 256 bytes. This has been fixed now and I have succesfully uploaded a WASM blob into my local Substrate (2.0.0) dev chain with following code:

```python
import os
from substrateinterface import SubstrateInterface, SubstrateRequestException, Keypair

substrate = SubstrateInterface(
    url="http://127.0.0.1:9933",
    address_type=42,
    type_registry_preset='default'
)

keypair = Keypair.create_from_uri('//Alice', address_type=42)

path = os.path.join(os.path.dirname(__file__), 'erc20.wasm')
with open(os.path.abspath(path), 'rb') as fp:
    code_bytes = fp.read()


call = substrate.compose_call(
    call_module='Contracts',
    call_function='put_code',
    call_params={
        'code': '0x{}'.format(code_bytes.hex())
    }
)

extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)

try:
    result = substrate.submit_extrinsic(extrinsic)

    print('Extrinsic hash: {}'.format(
        result['extrinsic_hash']
    ))

except SubstrateRequestException as e:
    print("Failed to send: {}".format(e))

```

Does this work for you too?

**Comment by lana-shanghai** [comment]
Fantastic, thank you! I will try and will let you know.

**Comment by lana-shanghai** [comment]
Sooo, connectivity to the canvas node - yes, submit extrinsic with contract.putCode - successful! 

What is strange: in the __init__.py file there is a result_handler function called in submit_extrinsic, and it returns the block_hash and whether the transaction is finalized, I tried to print out the block hash and the finalization status, but it returns None. Do you know why it might happen? Because otherwise how can I search for the hash, the search only allows to look for block hashes (I mean in the canvas UI). 

Also, when you go to the block hash, and find the extrinsic, it shows that it is successful, but the contract code hash isn't fully printed out and there is no "copy" button. It is super non useful! Do you know a way to get it out of there somehow?.. With the interface maybe? Attached is the screenshot. 

<img width="1370" alt="Screenshot 2020-11-20 at 16 55 49" src="https://user-images.githubusercontent.com/31368580/99820725-7201d480-2b51-11eb-9afc-025fc57da136.png">

**Comment by arjanz** [comment]
Good to hear that! :) 

Did you use the `wait_for_inclusion` or `wait_for_finalization` keyword arg? For example `substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)` will block until extrinsic is included in a block and then the `block_hash` is filled. 

Note that this only works for websocket connections and not over HTTP.

**Comment by lana-shanghai** [comment]
Worked! I'll keep playing with it and see if there's anything else to complain about :D
