### ISSUE TITLE
upload_wasm invalid

### ISSUE THREAD

**Issue by deuszx** [polkascan/py-substrate-interface#313]
There is not [`put_code`](https://github.com/polkascan/py-substrate-interface/blob/master/substrateinterface/contracts.py#L603) function in the `Contracts` pallet. Instead, it's called [`upload_code`](https://github.com/Cardinal-Cryptography/substrate/blob/master/frame/contracts/src/lib.rs#L584).

**Comment by arjanz** [comment]
You're right, `put_code` got removed in https://github.com/paritytech/substrate/commit/dc02c65a5c0001c2d87452cbdac47451f2c52eac 

I'll make a PR for this
