### ISSUE TITLE
Compose call

### ISSUE THREAD

**Issue by xakbel** [polkascan/py-substrate-interface#315]
Hi. When I try to send any transaction via compose_call I get this error. Same thing when I try to look at other people's extrinsic's.
I use the public rpc for hydradx.
Can you help me?

`substrateinterface.exceptions.SubstrateRequestException: {'code': 1002, 'message': 'Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\n\n    0: 0x39935f - <unknown>!rust_begin_unwind\n    1: 0x575c - <unknown>!core::panicking::panic_fmt::hd28c67e025192d49\n    2: 0x15b844 - <unknown>!TaggedTransactionQueue_validate_transaction\n', 'data': 'RuntimeApi("Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\\nWASM backtrace:\\n\\n    0: 0x39935f - <unknown>!rust_begin_unwind\\n    1: 0x575c - <unknown>!core::panicking::panic_fmt::hd28c67e025192d49\\n    2: 0x15b844 - <unknown>!TaggedTransactionQueue_validate_transaction\\n")'}
`

**Comment by arjanz** [comment]
Seems like HydraDX is not using the standard `MultiAddress` type for an Address but an `AccountId` type. At the moment, the library can't auto-detect this, so you will have to specify a type-override manually for this network:

```python
custom_type_registry = {
    "types": {
        "Address": "AccountId"
    }
}

substrate = SubstrateInterface(
    url="wss://rpc.hydradx.cloud",
    type_registry=custom_type_registry
)
```

Is this working for you?

**Comment by BlackCat99578** [comment]
Give me bridge

**Comment by arjanz** [comment]
> Give me bridge

What do you mean by this?

**Comment by xakbel** [comment]
> Is this working for you?
Yes. Thanks!

**Comment by arjanz** [comment]
I just released a new version that has auto-detection for `Address` and `ExtrinsicSignature` types stored in the metadata, so manually specifying the Address type should not be necessary anymore: https://github.com/polkascan/py-substrate-interface/releases/tag/v1.5.0
