### ISSUE TITLE
Add multi query documentation

### ISSUE THREAD

**Issue by gabrieljaegerde** [polkascan/py-substrate-interface#332]
There are currently examples for querying a single storage entry as well as querying all entries but there is no documentation on how to query the identities of 2 wallets together in one query for example.

I would assume this is currently possible (with query_map?) and an example in the docs would be much appreciated.

**Comment by arjanz** [comment]
Currently this isn't possible yet unfortunately, the `query_map()` is currently only retrieving all storage keys for provided storage function. But this wouldn't be much work to implement a new `query_multi()` function, that accepts a list of `StorageKey` objects, like [the way subscibe_storage()](https://polkascan.github.io/py-substrate-interface/usage/subscriptions/#subscribe-to-multiple-storage-keys)  works now. 

I'll create and a PR later for this.

**Comment by gabrieljaegerde** [comment]
Perfect.

**Comment by gabrieljaegerde** [comment]
Thank you! 😄
