### ISSUE TITLE
remove '==' requirements (exact version requirements)

### ISSUE THREAD

**Issue by moshemalawach** [polkascan/py-substrate-interface#35]
Hello,

Is it possible to remove the '==' in requirements for versions? 
It breaks any kind of application using your library, as all libraries have different version requirements.

Thanks!

**Comment by arjanz** [comment]
Definitely, that will make more sense

**Comment by arjanz** [comment]
Pushed to PYPI: https://pypi.org/project/substrate-interface/0.9.21/

**Comment by moshemalawach** [comment]
Wow that's great, thank you!
