### ISSUE TITLE
Unable to parse contract events

### ISSUE THREAD

**Issue by deep-ink-ventures** [polkascan/py-substrate-interface#365]
I am facing multiple problems on parsing events.

1. Every now and then the event data is bytes.

That is not happen all the times and so far I think it only occurs on `u32`, but I am not sure. The event data is then a `str`, e.g. `\x00\x01\x00\x00\x00` that I then have to convert via `bytes(x, 'utf-8'))` in order to feed it to `ScaleBytes`.

It's hacky but seems to work, however, more seriously:

2. `NotImplementedError: Decoder class for "ink::<source/hash from json goes here>::0" not found` is happening all the time

I'm not able at all to parse events at all. First of all, the Events are within the `ContractEmitted` part of the dict, not `ContractExecution` as mentioned in the str docs.

Is there an example on how to actually do this? I'm fetching a block and want to parse the event. I have the json metadata and can instantiate a contract code with is.

**Comment by arjanz** [comment]
What is the definition of type with `id: 0` in the metadata.json?

Also, which version of Ink! is in `language` property?

Is there a way for me to reproduce this with the metadata.json and an ws endpoint where the contract is deployed (or WASM code)? Then I can do some debugging for you.

**Comment by arjanz** [comment]
> I'm not able at all to parse events at all. First of all, the Events are within the `ContractEmitted` part of the dict, not `ContractExecution` as mentioned in the str docs.

This is [the part of the code ](https://github.com/polkascan/py-substrate-interface/blob/298c35cc8c2565afba421cbdef77e035ab61a8e6/substrateinterface/contracts.py#L487-L491) where the bytes of the `ContractEmitted` get decoded into a `ContractEvent` ScaleType.

**Comment by deep-ink-ventures** [comment]
Thanks!

Yes, you can do that here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnode.genesis-dao.org#/explorer

https://github.com/deep-ink-ventures/genesis-dao-service/blob/main/wasm/dao_asset_contract.json is the metadata.
https://github.com/deep-ink-ventures/genesis-dao-service/blob/main/wasm/dao_asset_contract.wasm is the wasm
https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/contracts/extensions/dao-assets-contract/src/lib.rs is creating the problem

I use this code:

```python
            contract_code = ContractCode.create_from_contract_files(
                wasm_file=wasm_path,
                metadata_file=json_path,
                substrate=substrate_service.substrate_interface,
            )

            data = contract_code.metadata.generate_constructor_data(name="new", args={"asset_id": 1})

            call = .substrate_interface.compose_call(
                call_module="Contracts",
                call_function="instantiate_with_code",
                call_params={
                    "value": 0,
                    "gas_limit": {"ref_time": 2599000000, "proof_size": 1199038364791120855},
                    "storage_deposit_limit": None,
                    "code": "0x{}".format(contract_code.wasm_bytes.hex()),
                    "data": data.to_hex(),
                    "salt": uuid4().hex,
                },
            )
```

**Comment by arjanz** [comment]
> > > I'm not able at all to parse events at all. First of all, the Events are within the `ContractEmitted` part of the dict, not `ContractExecution` as mentioned in the str docs.
> > 
> > 
> > This is [the part of the code ](https://github.com/polkascan/py-substrate-interface/blob/298c35cc8c2565afba421cbdef77e035ab61a8e6/substrateinterface/contracts.py#L487-L491) where the bytes of the `ContractEmitted` get decoded into a `ContractEvent` ScaleType.
> 
> This is for parsing the receipt, isn't it? I want to parse events.

This is for the contract events. The triggered events of an (contract call) extrinsic are part of the receipt

**Comment by deep-ink-ventures** [comment]
I fundamentally not understand what you are doing here.

I have an event listener via the `get_block()` method and want to parse the event contained within. I don't want to look at receipts nor doing a call. Can you enlighten me what I'm missing here?

**Comment by deep-ink-ventures** [comment]
Yay! It works. Thank you.
