### ISSUE TITLE
Async interface

### ISSUE THREAD

**Issue by zhoujs93** [polkascan/py-substrate-interface#367]
Hi, 

I have the following code:
```

```

Do you know if there is a way to speed up the process ? 

Does the substrate support asynchronous function ?

Thanks

**Comment by arjanz** [comment]
Unfortunately, no real async support yet. We are currently working though on a version 2 of the libraries, which will have asyncio support.

Until then you could work with threads, but there are some things to consider:

* An instance of SubstrateInterface is not thread-safe, so a thread should have a dedicated instance. Instances should not be shared across threads.
* Generating extrinsics and submitting simultaneously could lead to race conditions with the provided nonce, so that should also be provided manually.

I tested this in the example below:

```python
from concurrent.futures import ThreadPoolExecutor
from scalecodec import GenericExtrinsic
from substrateinterface import SubstrateInterface, Keypair, ExtrinsicReceipt


def submit_extrinsic(extrinsic: GenericExtrinsic) -> ExtrinsicReceipt:
    substrate_worker = SubstrateInterface(
        url="ws://127.0.0.1:9944"
    )
    print(f'> Submitting extrinsic: 0x{extrinsic.extrinsic_hash.hex()}')
    return substrate_worker.submit_extrinsic(extrinsic, wait_for_inclusion=True)


substrate = SubstrateInterface(
    url="ws://127.0.0.1:9944"
)

keypair = Keypair.create_from_uri('//Alice')

call = substrate.compose_call(
        call_module='Balances',
        call_function='transfer_keep_alive',
        call_params={
            'dest': '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty',
            'value': 1 * 10 ** 15
        }
    )

with ThreadPoolExecutor(max_workers=4) as executor:

    # Manually supply nonce because otherwise it will cause race conditions and discarded tx
    nonce = substrate.get_account_nonce(keypair.ss58_address)

    futures = []

    # Creating and submitting tasks to the executor

    extrinsic = substrate.create_signed_extrinsic(
        call=call,
        keypair=keypair,
        era={'period': 64},
        nonce=nonce
    )
    futures.append(executor.submit(submit_extrinsic, extrinsic))

    extrinsic = substrate.create_signed_extrinsic(
        call=call,
        keypair=keypair,
        era={'period': 64},
        nonce=nonce + 1
    )
    futures.append(executor.submit(submit_extrinsic, extrinsic))

    extrinsic = substrate.create_signed_extrinsic(
        call=call,
        keypair=keypair,
        era={'period': 64},
        nonce=nonce + 2
    )
    futures.append(executor.submit(submit_extrinsic, extrinsic))

    extrinsic = substrate.create_signed_extrinsic(
        call=call,
        keypair=keypair,
        era={'period': 64},
        nonce=nonce + 3
    )
    futures.append(executor.submit(submit_extrinsic, extrinsic))

    # Collect results
    for future in futures:
        result = future.result()
        print(f'* Extrinsic "{result.extrinsic_hash}" included in block "{result.block_hash}"')
```

Hope this helps!

**Comment by zhoujs93** [comment]
> Unfortunately, no real async support yet. We are currently working though on a version 2 of the libraries, which will have asyncio support.
> 
> Until then you could work with threads, but there are some things to consider:
> 
> * An instance of SubstrateInterface is not thread-safe, so a thread should have a dedicated instance. Instances should not be shared across threads.
> * Generating extrinsics and submitting simultaneously could lead to race conditions with the generated nonce, so that should also be provided manually.
> 
> I tested this in the example below:
> 
> ```python
> from concurrent.futures import ThreadPoolExecutor
> from scalecodec import GenericExtrinsic
> from substrateinterface import SubstrateInterface, Keypair, ExtrinsicReceipt
> 
> 
> def submit_extrinsic(extrinsic: GenericExtrinsic) -> ExtrinsicReceipt:
>     substrate_worker = SubstrateInterface(
>         url="ws://127.0.0.1:9944"
>     )
>     print(f'> Submitting extrinsic: 0x{extrinsic.extrinsic_hash.hex()}')
>     return substrate_worker.submit_extrinsic(extrinsic, wait_for_inclusion=True)
> 
> 
> substrate = SubstrateInterface(
>     url="ws://127.0.0.1:9944"
> )
> 
> keypair = Keypair.create_from_uri('//Alice')
> 
> call = substrate.compose_call(
>         call_module='Balances',
>         call_function='transfer_keep_alive',
>         call_params={
>             'dest': '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty',
>             'value': 1 * 10 ** 15
>         }
>     )
> 
> with ThreadPoolExecutor(max_workers=4) as executor:
> 
>     # Manually supply nonce because otherwise it will cause race conditions and discarded tx
>     nonce = substrate.get_account_nonce(keypair.ss58_address)
> 
>     futures = []
> 
>     # Creating and submitting tasks to the executor
> 
>     extrinsic = substrate.create_signed_extrinsic(
>         call=call,
>         keypair=keypair,
>         era={'period': 64},
>         nonce=nonce
>     )
>     futures.append(executor.submit(submit_extrinsic, extrinsic))
> 
>     extrinsic = substrate.create_signed_extrinsic(
>         call=call,
>         keypair=keypair,
>         era={'period': 64},
>         nonce=nonce + 1
>     )
>     futures.append(executor.submit(submit_extrinsic, extrinsic))
> 
>     extrinsic = substrate.create_signed_extrinsic(
>         call=call,
>         keypair=keypair,
>         era={'period': 64},
>         nonce=nonce + 2
>     )
>     futures.append(executor.submit(submit_extrinsic, extrinsic))
> 
>     extrinsic = substrate.create_signed_extrinsic(
>         call=call,
>         keypair=keypair,
>         era={'period': 64},
>         nonce=nonce + 3
>     )
>     futures.append(executor.submit(submit_extrinsic, extrinsic))
> 
>     # Collect results
>     for future in futures:
>         result = future.result()
>         print(f'* Extrinsic "{result.extrinsic_hash}" included in block "{result.block_hash}"')
> ```
> 
> Hope this helps!

Thanks, I was also able to do it through concurrent.futures

Also, I saw the tip argument for submitting transactions in the create_signed_extrinsic as well. Do you know if this supports other blockchains aside from polkadot as well ? Also, how would we find the asset_id for the tip ? 

Thanks !

**Comment by arjanz** [comment]
It basically depends on which "signed extensions" are active for the Substrate based blockchains out there, but almost all have the `ChargeTransactionPayment` extension enabled. The tip argument will be automatically ignored if the extension is not found.

The `asset_id` argument is only needed when the `ChargeAssetTxPayment` extension is active, but this is afaik only the case for Acala. 

You can check which signed extensions are active using: `substrate.get_metadata().get_signed_extensions()`

**Comment by zhoujs93** [comment]
> It basically depends on which "signed extensions" are active for the Substrate based blockchains out there, but almost all have the `ChargeTransactionPayment` extension enabled. The tip argument will be automatically ignored if the extension is not found.
> 
> The `asset_id` argument is only needed when the `ChargeAssetTxPayment` extension is active, but this is afaik only the case for Acala.
> 
> You can check which signed extensions are active using: `substrate.get_metadata().get_signed_extensions()`

Thank you for the help, and I guess the tip argument would be based on the currency of the substrate based block chain right ?

Thanks !

**Comment by arjanz** [comment]
> Thank you for the help, and I guess the tip argument would be based on the currency of the substrate based block chain right ?

Yes absolutely!

**Comment by zhoujs93** [comment]
> > Thank you for the help, and I guess the tip argument would be based on the currency of the substrate based block chain right ?
> 
> Yes absolutely!

Hi, so I tried running the above function with concurrent.futures but after while I noticed that it would just get stuck at the function and it seemed like the transaction was not getting a response back. 

Do you have any suggestions for this ? I am passing in the args of wait_for_inclusion = True and wait_for_finalization = True when calling the function, or do you suspect that this is due to the @retry decorator ?

**Comment by zhoujs93** [comment]
> > Thank you for the help, and I guess the tip argument would be based on the currency of the substrate based block chain right ?
> 
> Yes absolutely!
