### ISSUE TITLE
Make websocket timeout configurable

### ISSUE THREAD

**Issue by johnuopini** [polkascan/py-substrate-interface#371]
I am having issues with an endpoint that basically hangs and my job stays there forever waiting for timeout as timeout is currently hardcoded to 2**32, can we have a constructor param to specify default timeout?

**Comment by arjanz** [comment]
It is actually already possible to provide all available options when creating the websocket connection. There are some defaults atm, but nothing is hardcoded.

For example:

```python
substrate = SubstrateInterface(url='127.0.0.1', ws_options={'timeout': 10})
``` 

For all available options, see: https://websocket-client.readthedocs.io/en/latest/core.html#websocket._core.create_connection

**Comment by johnuopini** [comment]
Awesome, at least now searching for "timeout" in the issues might help someone :)
Thanks
