### ISSUE TITLE
support for ImOnline module

### ISSUE THREAD

**Issue by Maharacha** [polkascan/py-substrate-interface#390]
I'm trying to use the ImOnline module https://polkadot.js.org/docs/kusama/storage/#receivedheartbeatsu32-u32-optionbool with no success.
Something like this:
```
    received_heartbeats = substrate.query(
        module='ImOnline',
        storage_function='ReceivedHeartbeats',
        params=[ss58_decode("F7jUQyYybzQJMnfoYninC1G1j6BCkj4MtJps7z87w2Sxwat")]
    )
```
Is this not supported or am I doing something wrong?

**Comment by freshsalis** [comment]
I tried the same approach too and I got `substrateinterface.exceptions.StorageFunctionNotFound: Pallet "ImOnline" not found`

**Comment by arjanz** [comment]
It seems since a recent runtime upgrade, the pallet `ImOnline` is removed from Polkadot/Kusama. It's not present in the Metadata anymore, checked with PolkadotJS.

**Comment by arjanz** [comment]
More info: https://github.com/paritytech/polkadot-sdk/pull/3902

**Comment by Maharacha** [comment]
> More info: [paritytech/polkadot-sdk#3902](https://github.com/paritytech/polkadot-sdk/pull/3902)

Oh interesting. Not related to this library then. Thanks for fast response!
