### ISSUE TITLE
Add CheckMetadataHash signed extension support

### ISSUE THREAD

**Issue by arjanz** [polkascan/py-substrate-interface#391]
The `CheckMetadataHash` signed extension enables the new metadata hash verification feature that was approved as
[RFC78](https://polkadot-fellows.github.io/RFCs/approved/0078-merkleized-metadata.html).

See https://github.com/polkadot-fellows/runtimes/pull/337

**Comment by PierreBesson** [comment]
The `CheckMetadataHash` signed extension have been activated on Westend and Westend system parachains so they can now be tested in those networks.
