### ISSUE TITLE
Substrateinterface block info fetching bug polkadot

### ISSUE THREAD

**Issue by GeorgeVSV** [polkascan/py-substrate-interface#396]
I currently face  issues with fetching block information  via  polkadot websocket endpoint (using substrateinterface lib in Python) for  blocks with specific transaction type, here are few samples:

Block  number : 21473809
Transaction type : convictionvoting (remove_vote)
Error  text:  ValueError: Index '20'' not present in Enum type mapping
![image](https://github.com/polkascan/py-substrate-interface/assets/112613534/5f42a6f9-d359-42bb-818c-850a1447ad6a)

Block  number : 21473810
Transaction type : balances (transfer_allow_death)
Error text:  RemainingScaleByteEmptyException: Decoding <GenericExtrinsic> - Current offset: 108 / length: 148
![image](https://github.com/polkascan/py-substrate-interface/assets/112613534/7027e7a8-23b8-407b-842a-784a05437025)

I would be grateful for any help

**Comment by arjanz** [comment]
I didn't encounter any problems when using `substrate.get_extrinsics(block_number=21473810)` myself. Just to double-check, are you using the latest versions of `substrate-interface` and `scalecodec`?

**Comment by GeorgeVSV** [comment]
@arjanz  Hi! The problem was with scalecodec, after version updating the problem was solved, thank you!
