### ISSUE TITLE
Substrateinterface block info fetching bug polkadex

### ISSUE THREAD

**Issue by GeorgeVSV** [polkascan/py-substrate-interface#397]
I  currently face  issues with fetching block information  via  polkadex websocket endpoint  (using substrateinterface lib in Python) for  blocks with specific transaction type, here are few samples:

Block  number : 7275594
Transaction type : stacking (unbound)
Error  text:  RemainingScaleBytesNotEmptyException: Decoding <GenericExtrinsic> - Current offset: 110 / length: 140
![image](https://github.com/polkascan/py-substrate-interface/assets/112613534/33a5eb0c-44c5-4109-81f8-0eb4c1285657)

Block  number : 7275821
Transaction type : system(remark)
Error text:  ValueError: Index '9' not present in Enum type mapping
![image](https://github.com/polkascan/py-substrate-interface/assets/112613534/73e37970-e218-41bb-bda4-4beb5024a5cc)

I would be grateful for any help

**Comment by arjanz** [comment]
See https://github.com/polkascan/py-substrate-interface/issues/396#issuecomment-2214401971

**Comment by GeorgeVSV** [comment]
@arjanz Hi! This problem also was solved by updating scalecodec, so the issues can be closed
