### ISSUE TITLE
Storage calls on Westend network fail

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-substrate-interface#43]
Hi,
I'm making a call like was described in the README on the Westend network:
```
balance_info = substrate.get_runtime_state(
    module='System',
    storage_function='Account',
    params=['5FQhydxUyKtYeo9M4DsX3Cogm1u6bKF1KSwFikxhmFfydV7m'],
    block_hash="0x16a8af5d8f1d9a6adcc813dc2e77e58c315da5304378207e3037a25857a09922"
).get('result')
```
And get the following error (doesn't happen in Polkadot or in any other (non-storage) Westend call):
```
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 69 / length: 72
```
Debugging I've found out that MetadataV12Decoder is used. The version substrate-interface is 0.9.25 and scalecodec 0.10.26. 
Please advise what can be done and whether this is really an issue.

Thanks,
Pavel

**Comment by arjanz** [comment]
This was due to a type definition change in that storage call since last runtime upgrade of Westend, fixed in latest release
