### ISSUE TITLE
Reuse websocket connection

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-substrate-interface#46]
I'm currently overriding the `rpc_request` function to be able to reuse a websocket connection, but having to use this package in more than one context in the project, makes it not convenient.
Any plans to implement this?
Thanks!

**Comment by arjanz** [comment]
Can you provide an example how you want to reuse the websocket connect? Would it suffice to pass an optional websocket connection argument? 

And I'm also curious how you combined the async with non async in your code, maybe we can combine some of the best practices to integrate this with the library..

**Comment by pavelrib** [comment]
Sure. I must admit that our usage of the websocket is non-async, so it might need some additional parameter in your code to preserve backwards compatability. That's our overriding code:
```
class PolkadotNodeClient(substrateinterface.SubstrateInterface):
    def __init__(self,
                 websocket_wrapper: websocket.WebsocketWrapper,
                 requests_wrapper: requests.RequestsWrapper,
                 **kwargs):
        super(PolkadotNodeClient, self).__init__(**kwargs)
        self._is_websocket_url = urlparse(self.url).scheme in defines.URL_WEBSOCKET_SCHEMES
        if self._is_websocket_url:
            self.websocket_wrapper = websocket_wrapper
        else:
            self.requests_wrapper = requests_wrapper

    def rpc_request(self,
                    method: str,
                    params: typing.List,
                    result_handler: typing.Optional[typing.Callable] = None) -> typing.Dict:
        """
        Overriding the original rpc request function to support websocket reuse.
        """
        if self._is_websocket_url:
            json_body = self.websocket_wrapper.jsonrpc2_websocket_call(method=method,
                                                                       params=params,
                                                                       request_id=self.request_id,
                                                                       get_result=False)
        else:
            if result_handler:
                raise substrate_interface_exceptions.ConfigurationError(
                    "Result handlers only available for websockets (ws://) connections",
                )
            payload = self.websocket_wrapper.get_jsonrpc2_call_parameters(method=method,
                                                                          params=params,
                                                                          request_id=self.request_id)
            raw_response = self.requests_wrapper.make_request_post(url=self.url,
                                                                   data=json.dumps(payload),
                                                                   headers=self.default_headers)
            json_body = self.requests_wrapper.parse_json_response(raw_response)

        return json_body
```
the websocket received here as an argument is already connected (the surrounding infra takes care of that and reinitializing the websocket in the case of network failure). 
Same goes for requests in `RequestsWrapper` (although the connection itself doesn't need to be initialized, we initialize ssl related stuff there, if needed).

An optional parameter would be more fitting for my code, but I think a better way to go about it is lazy connection. Something like this:
```
def init_websocket():
    self.websocket = websocket.create_connection(self.node_host, timeout=self.DEFAULT_TIMEOUT_IN_SECONDS)

def rpc_request():
    ....
    try:
        if not self.websocket:
             init_websocket()
        self.websocket.call()
    except NetworkError:
        init_websocket()
    ....
```   
WDYT?

**Comment by arjanz** [comment]
I like the idea to be able to optionally pass along a websocket connection handler on init which will be used for communication, that is already much more efficient than make a new connection for every request. Then it's up to the application to manage this connection.

**Comment by pavelrib** [comment]
Yeah, totally fine by me.

**Comment by arjanz** [comment]
@pavelrib 0.10.0 has just been released, where websocket connections being reused within the library during the lifetime of a SubstrateInterface instance when providing the `url` parameter, but now is also possible to pass through a external connection with the `websocket` argument.
