### ISSUE TITLE
Signing of proxy transaction creates invalid transaction signature

### ISSUE THREAD

**Issue by carumusan** [polkascan/py-substrate-interface#49]
I'm trying to sign a proxy transaction but the polkadot node is giving me an invalid transaction error. Example here with addresses redacted:
```
>>> print(proxy_call.value)
{'call_args': {'call': {'call_args': {'targets': [<nomination_address_list>]},
                        'call_function': 'nominate',
                        'call_module': 'Staking'},
               'force_proxy_type': 'Staking',
               'real': '<controller_address>'},
 'call_function': 'proxy',
 'call_module': 'Proxy'}
```
```
nomination_extrinsic = polkadot_connection.create_signed_extrinsic(call=proxy_call, keypair=<controller_proxy_keypair>)
result = polkadot_connection.submit_extrinsic(nomination_extrinsic, wait_for_inclusion=True)
```
Throws this exception
`substrateinterface.exceptions.SubstrateRequestException: {'code': 1010, 'message': 'Invalid Transaction', 'data': 'Transaction has a bad signature'}`

**Comment by carumusan** [comment]
Weirdly this may be related to the length of the call data. I noticed that if I reduce the nomination address list and remove the proxy it succeeds. If I increase the list length to about 6 addresses it fails. I haven't pin pointed where in the code the length could affect it. Any ideas?

**Comment by arjanz** [comment]
Ah this is valuable feedback.. I also had problems creating extrinsics which contained large contract WASM binaries and suspect it's related. I'll look in the specs if the composition of the extrinsic payload changes for large extrinsics.

**Comment by arjanz** [comment]
I pushed a release 0.9.35 which now should generate correct signatures for extrinsics > 256 bytes. Does this solves your issue as well?

**Comment by carumusan** [comment]
The proxy call is now working, thanks for the quick turnaround.
