### ISSUE TITLE
a exception with substrate.get_storage  | scalecodec-Decoder

### ISSUE THREAD

**Issue by haoming06** [polkascan/py-substrate-interface#5]
I try to use substrate.get_storage with SubstrateInterface package, there is a error  throws`throwpython3.7/site-packages/scalecodec-0.1.0-py3.7.egg/scalecodec/base.py", line 243, in get_decoder_class NotImplementedError: Decoder class for "MetadataRecord<AccountId, Hash, Balance, Moment>" not found` ,

`identity = substrate.get_storage( block_hash=obj['block_hash'], module="OrlModule", function="Identity", params= address.replace('0x',''), return_scale_type=storage_call.get_return_type(), hasher=storage_call.type_hasher, metadata = ? )` Is the metadata a dict? how to set it

**Comment by arjanz** [comment]
Storage call are much intuitive since previous major release:

```
substrate.get_runtime_state(
        module='Balances',
        storage_function='FreeBalance',
        params=['EaG2CRhJWPb7qmdcJvy3LiWdh26Jreu9Dx6R1rXxPmYXoDk']
    ).get('result')
```

This will probably solve a lot of questions
