### ISSUE TITLE
Support of Python3.6 in the latest versions

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-substrate-interface#50]
Part of our project runs with Python 3.6.10 and the latest version of this package available there seems to be 0.9.20.
Any way to make the versions after that compatible with Python 3.6?

**Comment by arjanz** [comment]
Support was dropped because of incompatibility of asyncio usage, but I already found out how to make it work for Python 3.6: https://github.com/polkascan/py-substrate-interface/pull/34 

I'll make a backwards compatible change soon to re-add 3.6 support

**Comment by arjanz** [comment]
Deploy to PyPI: https://pypi.org/project/substrate-interface/0.9.34/
