### ISSUE TITLE
Transaction info when constructing the transaction offline

### ISSUE THREAD

**Issue by pavelrib** [polkascan/py-substrate-interface#51]
In the polkadot documentation they propose to construct the transaction this way:
```
import { methods } from "@substrate/txwrapper";

const unsigned = methods.balances.transferKeepAlive(
  {
    dest: "15vrtLsCQFG3qRYUcaEeeEih4JwepocNJHkpsrqojqnZPc2y",
    value: 500000000000,
  },
  {
    address: "121X5bEgTZcGQx5NZjwuTjqqKoiG8B2wEAvrUFjuw24ZGZf2",
    blockHash: "0x1fc7493f3c1e9ac758a183839906475f8363aafb1b1d3e910fe16fab4ae1b582",
    blockNumber: 4302222,
    genesisHash: "0xe3777fa922cafbff200cadeaea1a76bd7898ad5b89f7848999058b50e715f636",
    metadataRpc, // must import from client RPC call state_getMetadata
    nonce: 2,
    specVersion: 1019,
    tip: 0,
    eraPeriod: 64, // number of blocks from checkpoint that transaction is valid
    transactionVersion: 1,
  },
  {
    metadataRpc,
    registry, // Type registry
  }
);
```
The `dest` and `value` parameters are indeed the parameters of the transfer function, but the additional info parameter doesn't appear in this library `compose_call` function. I assume not all is needed, but at least the tip and the source address should be set by me, no? Is it possible to construct it the same way in the current state of the function?

**Comment by pavelrib** [comment]
Sorry, missed the `generate_signature_payload` function. I see that the resulting payload differs there a bit from what I posted:
```
        payload_dict = {
            'call': call_data,
            'era': era,
            'nonce': nonce,
            'tip': tip,
            'specVersion': self.runtime_version,
            'genesisHash': genesis_hash,
            'blockHash': block_hash
        }
```
For instance, it doesn't have the `address` field. Is this intended?

**Comment by arjanz** [comment]
If you want to generate a transaction with a certain mortality you can compose it as follows:

```python
keypair = Keypair.create_from_mnemonic(mnemonic, address_type=0)

balance_info = substrate.get_runtime_state(
    module='System',
    storage_function='Account',
    params=[keypair.ss58_address],
).get('result')

call = substrate.compose_call(
    call_module='Balances',
    call_function='transfer_keep_alive',
    call_params={
        'dest': '15vrtLsCQFG3qRYUcaEeeEih4JwepocNJHkpsrqojqnZPc2y',
        'value': 500000000000
    }
)


extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair, era={'period': 64}, tip=0)
```

But this will retrieve needed parameters like current `nonce`, `blockHash`, `blockNumber`, `specVersion`, `transactionVersion ` and `genesisHash` on chain automatically, so you will not be able to generate an extrinsic payload offline as of now yet. 

The `substrate.generate_signature_payload` function you found is indeed intended to let for example `subkey` or another external signer create the signature (also offline), but except for the `nonce` this also does require some parameters to be retrieve on-chain so needs a connection to a node. `address` is not really necessary at this point, the result of `generate_signature_payload` can be signed with e.g.: 

```python 
signature_payload = substrate.generate_signature_payload(call=call, era={'period': 64, 'current': 2491553}, nonce=3, tip=0)
```

Generate signature on offline machine with the `signature_payload`:

```bash
echo -n "0503da04de6cd781c98acf0693dfb97c11011938ad22fcc476ed0089ac5aec3fe243070088526a7415020c001a0000000500000091b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c335e2767cb46536dc73cdb254775ee57cd2bd0fd1fae5052506607849ead9b333" | subkey sign --hex "target goose later shrug aisle sauce rule tip caution warrior coral family"
```

Submit extrinsic with generated signature (and match `nonce` and `tip` with generated signature payload):

```python
keypair = Keypair(ss58_address="12myuAQjnYtQ1j6AiSa8xzHncVufRHpUHr7D2BJfBuja2NGf")

# Create extrinsic
extrinsic = self.substrate.create_signed_extrinsic(
    call=call,
    keypair=keypair,
    nonce=nonce,
    signature=signature
)
result = self.substrate.submit_extrinsic(
    extrinsic=extrinsic
)
```

**Comment by arjanz** [comment]
Or of course use this library to generate the signature on the offline machine:

```python
keypair = Keypair.create_from_mnemonic("nature exchange gasp toy result bacon coin broccoli rule oyster believe lyrics")
signature = keypair.sign(signature_payload)
```

**Comment by pavelrib** [comment]
Wow, thank you for the detailed answer.
Just to make sure I understand  - why the address is not needed in the payload? How the network verifies I'm sending from a certain address?

**Comment by arjanz** [comment]
The network validates if the signature is signed with the keypair of the sender of the extrinsic. This is added in the latest step in the example above.

You could also verify it manually to try:

```python
keypair.verify(signature_payload, signature)
```

In the last step of the example

**Comment by pavelrib** [comment]
Great, this has been really helpful. Thank you!
