### ISSUE TITLE
latest block height

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [polkascan/py-substrate-interface#62]
Hi. I want to sign a transaction offline. you have used an object "era" containing "current" in your example as below: `era = {'period': 64, 'current': 22719}`  I guess that "current" is the height of the last block but I'm not sure. if it is, how can I get the last block height of a network like "Westend" using this library?

**Comment by arjanz** [comment]
You can get the last block height with: `substrate.get_block_number(block_hash=substrate.get_chain_head())`
