### ISSUE TITLE
'ExtrinsicReceipt' object has no attribute 'is_success'

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [polkascan/py-substrate-interface#63]
I can't get the receipt of my transaction. I run the following code :
`extrinsic = substrate.create_signed_extrinsic(
    call=call,
    keypair=keypair,
    era=era,
    nonce=nonce,
    signature=signature
)`

`receipt = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)`
`print(receipt['extrinsic_hash'])`
`print(receipt.is_success) # False`
`print(receipt.weight) # 216625000`
`print(receipt.total_fee_amount) # 2749998966`
`print(receipt.error_message['name']) # 'LiquidityRestrictions'`

I get the hash of transaction and this transaction is successful because I can find it in subscan but the receipt raises an error as below : 

`'ExtrinsicReceipt' object has no attribute 'is_success'`

**Comment by arjanz** [comment]
You have the latest version of `py-substrate-interface`? What Python version are you using?

Strange, that property really exists (https://github.com/polkascan/py-substrate-interface/blob/ab67c6f188b6aacecf2cc8ce7b405d7d30f1ffe7/substrateinterface/base.py#L2560) and the example https://github.com/polkascan/py-substrate-interface/blob/1c52819a839d70dc6563d5d5e058e0683a24ff8e/examples/balance_transfer.py works for me..

**Comment by skinderis** [comment]
there is a lint in the property name: **is_succes** instead of **is_success**

**Comment by arjanz** [comment]
Auch that's a painful one.. And I was convinced I wasn't dyslectic. I'm gonna fix that and pretend that didn't happen ;)
