### ISSUE TITLE
find all transfer transactions related to a specific account 

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [polkascan/py-substrate-interface#64]
Hi. how can I retrieve all transfer transactions related to a specific account?
by related transactions, I mean all the transfer transactions that this account received or sent coins in them.

**Comment by arjanz** [comment]
There is no index available to query this directly from the node, so you will need an application that harvest all transactions and events and adds those indices like https://github.com/polkascan/polkascan-os
