### ISSUE TITLE
SubstrateInterface get_block_number method raises TypeError if response has no "result"

### ISSUE THREAD

**Issue by vnavascues** [polkascan/py-substrate-interface#68]
Hi,

At Rotki we have experienced a `TypeError` calling `get_block_number` due to [how the response is processed](https://github.com/polkascan/py-substrate-interface/blob/master/substrateinterface/base.py#L732). It is one of the few methods that does not check whether the RPC call response exists or not. Besides, there is still some discrepancy in regard to how an empty/unexpected response is processed; some methods return `None` whilst others raise `SubstrateRequestException`.

Thanks for this library!

**Comment by arjanz** [comment]
This should indeed be more uniform and I think in case of no result, a consistent `None` would be the preferable return value. In case of invalid input a`ValueError` and `SubstrateRequestException` in case of an unexpected result. I will add this for next release.

**Comment by arjanz** [comment]
Released in v0.11.10, does this work for you guys?
