### ISSUE TITLE
[Feature request] Example of signing and submitting an extrinsic

### ISSUE THREAD

**Issue by faustow** [polkascan/py-substrate-interface#7]
Thanks for your work guys! I was just wondering if you would be so kind of providing an example of signing and submitting extrinsics in the README?
Thanks!

**Comment by EdwardAThomson** [comment]
Yeah, this is a feature I'd really like to. I see there is code for sending unsigned extrinisics, but not signed.

I've seen 2 attempts at creating bindings for Schnorrkel in Python:
1. https://github.com/holygits/schnorpy
1. https://gitlab.com/kauriid/schnorrpy/

Although perhaps the Polkascan team would feel more comfortable creating their own bindings.

**Comment by brenzi** [comment]
Another way of providing this would be a rust-library binding for python. That's what we did for our [JAVA android app](https://github.com/encointer/encointer-app/tree/master/encointer_android_app/encointer-api-native) too. Maybe our [encointer CLI client](https://github.com/encointer/encointer-node/tree/master/client) based on [substrate-api-client](https://github.com/scs/substrate-api-client) could easily be refactored into such a lib including a keystore.

**Comment by drandreaskrueger** [comment]
I hope I get an answer to this soon:

https://github.com/paritytech/substrate/issues/5180

then I think I have the scheme (plusminus what I still misunderstood) ready how to send a transaction. Will share the Python code then.

**Comment by EdwardAThomson** [comment]
Looks like we are getting close. Thanks for helping to push this along @drandreaskrueger

**Comment by drandreaskrueger** [comment]
Yes. See https://github.com/polkascan/py-substrate-interface/issues/10 there's also code to play with.

**Comment by emielvanderhoek** [comment]
We have been experimented with various approaches for signing and wrapping send-able txs (machine-interface & human interface). We have been working on a new w3f grant application to cover those features. That application should be ready on short term (weeks). We will share more information once we have it.

**Comment by arjanz** [comment]
Good news, today we've released a first version which makes creating and submitted of signed extrinsics possible: https://github.com/polkascan/py-substrate-interface#create-and-send-signed-extrinsics
