### ISSUE TITLE
Request: bundle rust binaries with python package

### ISSUE THREAD

**Issue by carumusan** [polkascan/py-substrate-interface#70]
Currently running a "pip install" requires that you have cargo and the appropriate rust toolchains installed. In some environments this can prove to be difficult and temperamental especially with nightly toolchains. It would be convenient if the python package included the rust binaries. This would speed up the install considerably and make it more reliable.

Here is an example of a github action that compiles and bundles rust binary using maturin: https://github.com/gukoff/dtparse/blob/master/.github/workflows/ci.yml

**Comment by carumusan** [comment]
Example of an environment that installing cargo is impossible is the latest version of google cloud functions, which does not let you install rust. It only lets you specify requirements.txt.

**Comment by arjanz** [comment]
Actually we are already using Maturin to create precompiled wheels for our RUST bindings like the sr25519 and ed25519 packages (e.g. https://pypi.org/project/py-sr25519-bindings/#files) We precompile manylinux1, MacOS and Windows for Python 3.7 - 3.9), so in many cases you don't need a RUST toolchain installed.

But apparently your environment for some reason cannot use the precompiled binaries and have to resort to compile from source.. 

Which OS/Python (or cloud platform) version are you using? 

Thanks for the Github action template, this is helpful. At the moment we are manually compiling on Mac/Windows and Linux, so we will check it out to save time and get a better CI for our RUST bindings.

**Comment by carumusan** [comment]
On my devlopement machine i'm using MacOS and pip install is installing from source. I don't know how pip install chooses the wheels but could it be because they are tagged with version 10.7 in their name?

**Comment by carumusan** [comment]
Tried a force reinstall on MacOS there and it downloaded the binaries. Must have been uploaded relatively recently as that wasn't the case a few weeks ago.
