### ISSUE TITLE
compose_call only works with dest=PUB_KEY

### ISSUE THREAD

**Issue by drandreaskrueger** [polkascan/py-substrate-interface#8]
When playing with

    compose_call( Balances, transfer, {'dest': dest,'value': value} )

 I got a lot of errors like

```
ValueError: Invalid checksum
ValueError: Invalid address length
ValueError: Invalid account index length
```

until I realized that I cannot (?) send to an 

    address (5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY) 

but must use the 

    PUB_KEY (0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d)

instead, for the `dest`:

```
payload = substrate.compose_call(call_module='Balances',
                                 call_function='transfer',
                                 call_params={'dest': dest,
                                              'value': value})
```

I suggest, you mention that the https://github.com/polkascan/py-substrate-interface#compose-call explanations?

**Comment by drandreaskrueger** [comment]
P.S.: Please also see https://github.com/paritytech/substrate/issues/5180 perhaps you have ideas how to solve it? Thanks.

**Comment by arjanz** [comment]
It should auto-detect the address format, but you were right, there was an issue with the auto-detection of whether the given argument is a public key, SS58 encoded AccountId or SS58 encoded AccountIndex. I assumed the SS58 encoded AccountId is always 47 chars long, but this was not the case.

Thanks for the feedback, I fixed it in https://github.com/polkascan/py-scale-codec/commit/650723e587c703a384892e1f167304686012737e so with a new pip install it should be fixed. 

Regarding your comment about subkey, I also asked a question in the Riot group 'Substrate Technical', but no answers there unfortunately. We also want to implement signing, so as soon as I have a solution I'll let you know.

**Comment by drandreaskrueger** [comment]
> so with a new pip install it should be fixed.

Oh wow, you're a star. That was VERY quick. Thanks a million!

**Comment by drandreaskrueger** [comment]
>  I also asked a question in the Riot group 'Substrate Technical',

Thanks a lot, @arjanz - any news?
