### ISSUE TITLE
Unable to call custom types for storage

### ISSUE THREAD

**Issue by afeezaziz** [polkascan/py-substrate-interface#81]
In the example of

`        native_pair = substrate.query(
            module='Exchange',
            storage_function='PairNative',
            params=[0])`

where 0 is a custom type PairNative which is U128, I am unable to get the result but getting `scalecodec.exceptions.RemainingScaleBytesNotEmptyException:`. I have passed the custom types as `custom_type_registry = load_type_registry_file("api/custom.json")` to enable to load the custom types. This only happens in storage but not extrinsics weirdly so.

**Comment by arjanz** [comment]
I have no context of your runtime, so it's impossible for me to debug, but a wild guess could be is to check if `PairNative` is not actually a `Compact<U128>`?
