### ISSUE TITLE
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: Current offset: 72 / length: 76

### ISSUE THREAD

**Issue by oggy95** [polkascan/py-substrate-interface#85]
Same error like this: https://github.com/polkascan/py-substrate-interface/issues/84

But I'm using kusama public node:
```
substrate = SubstrateInterface(
            url="wss://kusama-rpc.polkadot.io/", address_type=2, type_registry_preset='kusama')
```

**Comment by arjanz** [comment]
Can you provide a block_hash and function so I can reproduce this decoding error?

**Comment by oggy95** [comment]
An error occurs when try to compose and broadcast transaction:

```
try:
        call = substrate.compose_call(
            call_module='Balances',
            call_function='transfer',
            call_params={
                'dest': context["to"],
                'value': context["amount"]
            }
        )

        print(call)
        print("\n")
        keypair = {}

        keypair = Keypair.create_from_mnemonic(context["password"], address_type=ADDRESS_TYPE)

        extrinsic = substrate.create_signed_extrinsic(call=call, keypair=keypair)
        print(extrinsic)
        print("\n")
        result = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)
        print(result)
        print("\n")
        print("Extrinsic '{}' sent and included in block '{}'".format(result['extrinsic_hash'], result['block_hash']))
        return result['extrinsic_hash']

    except SubstrateRequestException as e:
        print("Failed to send: {}".format(e))
        return {"error": str(e)}
```

Some code was deleted from this. "context" - dictionary with necessary parameters.

**Comment by arjanz** [comment]
Did you update your type registries with `substrate.update_type_registry_presets()` (or updated `scalecodec` package to latest version)?  There has been runtime upgrades lately so this could be out of date

I also see you are using deprecated kwarg `address_type`, this will be dropped since its been replace by `ss58_format`.

**Comment by arjanz** [comment]
Also there has been some issues with the new `MultiAddress` type, I just pushed a fix for that

**Comment by oggy95** [comment]
Fixed by upgrade `scalecodec` package. Thank you :)
