### ISSUE TITLE
Broadcast multiple transactions simultaneously fails occasionally

### ISSUE THREAD

**Issue by haniyeh-habibi** [polkascan/py-substrate-interface#89]
Hi,
When i broadcast multiple transactions simultaneously just maybe one of them broadcast successfully

**Comment by haniyeh-habibi** [comment]
if i broadcast transactions one by one it will broadcast successfully but 2 or more transactions will fail and just one would broadcast

**Comment by arjanz** [comment]
Since latest release https://github.com/polkascan/py-substrate-interface/releases/tag/v0.12.1 subscription support is improved, so these kind of errors shouldn't occur anymore

**Comment by haniyeh-habibi** [comment]
Thanks.
