### ISSUE TITLE
compose_call() results in payload that makes sign-transaction crash

### ISSUE THREAD

**Issue by drandreaskrueger** [polkascan/py-substrate-interface#9]
N.B.: `subkey sign-transaction ...` v2.0.0 itself has a bug because why would it otherwise now suddenly fail with its own (May 2019) parameters, see "long story short" here: https://github.com/paritytech/substrate/issues/5180#issuecomment-597129861. But that does not mean that there is not a second bug in the Python code ... ;-)

---

Could it be that the `compose_call()` returns a faulty hex blob? Try this:

Get an old version of subkey that was working for sure:
```
git clone substrate
cd substrate
git checkout e74463feb2f79ef68a1515e7ad626d8695daa51d
cd subkey
cargo run -- sign-transaction     --call 0300ff408aa36b945720031fbb2e661fc9c9f1ed799be5369f991bbfce02103b5f0e44e514     --nonce 0     --suri //Alice///     --password password     --prior-block-hash f8349fe94e9fd86e8a85745bbb70a4d2d5f4d8fc32a1f8fc08088faf1840e705
```
that does *not crash* but results in

```
0x250281ffd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d820c9dae649279bc7323e3905b326d7a052c8ba3e644f4cf62ab97354df6167a226af6a7d0d90ed8a0a90261c7bd3512b08b487e77a8d254e76e335fdaabeb0a00000300ff408aa36b945720031fbb2e661fc9c9f1ed799be5369f991bbfce02103b5f0e44e514
```

but when I now swap the `--call` for **a payload output of your `compose_call()`** 
```
cargo run -- sign-transaction     --call a8040400ff8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48070010a5d4e8   --nonce 0     --suri //Alice///     --password password     --prior-block-hash f8349fe94e9fd86e8a85745bbb70a4d2d5f4d8fc32a1f8fc08088faf1840e705
```
the same command crashes with 
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
```

P.S.: Yes new version
```
pip install --upgrade substrate-interface
```
> Successfully installed scalecodec-0.9.19 substrate-interface-0.9.6

then I generated the above 'a8040400ff8eaf041....` payload like this (correct?):

```
import substrateinterface
substrate = substrateinterface.SubstrateInterface(url="ws://127.0.0.1:9944/")

BOB_ADDRESS = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty'

payload = substrate.compose_call(call_module='Balances',
                                 call_function='transfer',
                                 call_params={'dest': BOB_ADDRESS,
                                              'value': 1000000000000})
print (payload.replace("0x", ""))
```

**Comment by drandreaskrueger** [comment]
Hi @arjanz as we were discussing that same bug perhaps you can have a look?  Thanks.

**Comment by drandreaskrueger** [comment]
Finally got an answer over there https://github.com/paritytech/substrate/issues/5180#issuecomment-596852752 and s/he explained:

> your --call value needs to be an encoded Call representation, see https://substrate.dev/rustdocs/master/node_runtime/enum.Call.html. If that's not the case, this section in subkey/src/main.rs, ll 477 .... fails.

(Hello @arjanz @emielvanderhoek or anyone else:) Could you please double check whether your `compose_call() follows the correct recipe. 

Thanks

**Comment by drandreaskrueger** [comment]
I still think subkey sign-transaction v2.0.0 has a bug because why would it otherwise now suddenly fail with its own (May 2019) parameters, see "long story short" here: https://github.com/paritytech/substrate/issues/5180#issuecomment-597129861

But that ^ does not mean that perhaps there is a second bug in the Python code ... ;-)

The relevant code parts are:

`def compose_call(self, call_module, call_function, call_params=(), block_hash=None)`

https://github.com/polkascan/py-substrate-interface/blob/ff6801f6b370b26d67eb393dd14c01e0f511ee90/substrateinterface/__init__.py#L661-L686

and

`class ExtrinsicsDecoder(ScaleDecoder).__init__(...)`

https://github.com/polkascan/py-scale-codec/blob/c2d8e8408fb9c20d79bba684ee47618e5f646d0a/scalecodec/block.py#L25-L36


and

`.process()`


https://github.com/polkascan/py-scale-codec/blob/c2d8e8408fb9c20d79bba684ee47618e5f646d0a/scalecodec/block.py#L75-L215

right?

**Comment by emielvanderhoek** [comment]
All composeCall methods got unit tests.
https://github.com/polkascan/py-scale-codec/blob/master/test/test_extrinsic_payload.py
These unit tests took an external application (Polkadot JS Apps) as baseline (using: https://polkadot.js.org/apps/#/extrinsics).
Therefore we are very very confident that the output of composeCall is correct.

Please note that the current unit tests use runtime_version <= `kusama-1049`.
Runtime_version `kusama-1050` uses a different Address-type encoding and thus these unit test will very likely differ.

Today we learned from Parity Technologies that `subkey sign-transaction` has not been maintain over a year and we were recommended not to use this option of subkey.

Currently signing the composed calls remains off-scope for this project and we will not (cannot) dedicate any resources on this just now. We are preparing a new grant application to extend the library with signing methods. That may happen in the next few months.

**Comment by drandreaskrueger** [comment]
Thanks a lot @emielvanderhoek 

>  got unit tests.

Perfect.

> we are very very confident that the output of composeCall is correct.

Good. Thanks for confirming that.

So it is likely their code that is broken. --> 

> Today we learned from Parity Technologies that subkey sign-transaction 
> has not been maintain over a year

Not quite a year probably. Last May it still seemed to work. See the linked issue.

>  and we were recommended not to use  this option of subkey.

So what is the strategy in Python then?

>  That may happen in the next few months.

Too late for me.

**Comment by drandreaskrueger** [comment]
You are busy with other things, and this is outside your scope.

**Do you know other Pythonians who might be of help for me?**
 
I just want to send a transaction to a blockchain.  Why is this so impossibly difficult?

**Comment by drandreaskrueger** [comment]
Perhaps mention here https://github.com/polkascan/py-substrate-interface#compose-call that the following step -signing- is unsolved at the moment?

Because several people have actually pointed me to https://github.com/polkascan/py-substrate-interface#compose-call when I asked for how to do it in Python.

**Comment by drandreaskrueger** [comment]
continued in new issue: https://github.com/polkascan/py-substrate-interface/issues/10#issuecomment-597419520
