### ISSUE TITLE
Websocket connection ends without receiving newHeads

### ISSUE THREAD

**Issue by sanada08** [polkascan/py-substrate-interface#90]
I use method:chain_subscribeFinalizedHeads to get the latest head but connection  ends automatically without receiving data.

```
try:
    substrate = SubstrateInterface(
        url="wss://westend-rpc.polkadot.io",
    )
except ConnectionRefusedError:
    print("⚠️ No local Substrate node running, try running 'start_local_substrate_node.sh' first")
    exit()

# substrate.connect_websocket()
api = substrate.rpc_request("chain_subscribeFinalizedHeads",params=[])```.

Could you please provide any solutions. Is there any alternate method to subscribe the latest blocks in websocket.

**Comment by arjanz** [comment]
Subscriptions are not supported at the moment, the current library is intended to be used in a synchronous context. 

But somewhere along the roadmap we will make an async version that will support subscriptions.

**Comment by sanada08** [comment]
Thanks.

**Comment by arjanz** [comment]
@sanada08 Actually there is a way already which you can use subscription calls, although it will probably block your execution forever.

You can try:

```python
def result_handler(result):
    # Do something with the result
    print(result)

    # The subscription will block until an arbitrary value is returned, which will be the result of the `rpc_request`
    # return {'result': result, 'status': 'done'}


response = substrate.rpc_request(
    method="chain_subscribeFinalizedHeads",
    params=[],
    result_handler=result_handler
)

# {'result': result, 'status': 'done'}
print(response)
```

I already use this to determine when an extrinsic is included in a block or is finalized:

https://github.com/polkascan/py-substrate-interface/blob/ccb8fc4f36d80249755e538d7eef697b9384db0a/substrateinterface/base.py#L1632

There are some issues with concurrent subscriptions, I am working on a fix for this.

**Comment by arjanz** [comment]
Good news, since latest release https://github.com/polkascan/py-substrate-interface/releases/tag/v0.12.1 subscriptions are supported:

```python
def block_subscription_handler(obj, update_nr, subscription_id):

    print(f"New block #{obj['header']['number']} produced by {obj['author']}")


result = substrate.subscribe_block_headers(block_subscription_handler, include_author=True, finalized_only=True)
```
