### ISSUE TITLE
Proper close() and resource cleaning

### ISSUE THREAD

**Issue by maayank** [polkascan/py-substrate-interface#96]
In an app with many instances of SubstrateInterface over its lifetime, there is a leak of websocket connections where close() for the websocket connection is never called. I suggest either:
1. Implementing a close() function to have a canonical way to close such resources (i.e. if I missed similar items that need to be closed behind websocket)
2. State SubstrateInterface should be used once in a lifetime (e.g. singleton) - less preferable IMO :)

As a workaround, in the meantime I call my_substrate_instance.websocket.close() once I finish with the substrate instance.

**Comment by arjanz** [comment]
Probably a `with` statement makes sense, where the `__exit__` will take care of the cleanup.

So something like:
```
with SubstrateInterface(url="wss://rpc.polkadot.io") as substrate:
    events = substrate.query("System", "Events")
```

Will that work for you?

**Comment by arjanz** [comment]
Be aware though that every time a SubstrateInterface is instantiates there is overhead of establishing websocket connection, parsing metadata etc, so it would be recommended to keep the instances in a long term process.

**Comment by maayank** [comment]
For my specific code base I'd probably use it outside of the with paradigm, but it's most pythonic. Many thanks @arjanz !
